<div style="border:solid purple 2px; padding: 20px">

–í–∏–∫—Ç–æ—Ä–∏—è –ø—Ä–∏–≤–µ—Ç! üëã –ü–æ–∑–¥—Ä–∞–≤–ª—è—é —Å –ø–µ—Ä–≤—ã–º –≤—ã–ø–æ–ª–Ω–µ–Ω–Ω—ã–º –ø—Ä–æ–µ–∫—Ç–æ–º.
    
–ú–µ–Ω—è –∑–æ–≤—É—Ç –†—É—Å—Ç–∞–º –ú—É—Ä—Ç–∞–∑–∏–Ω, –∏ —è –±—É–¥—É –¥–µ–ª–∞—Ç—å —Ä–µ–≤—å—é –ø—Ä–æ–µ–∫—Ç–Ω–æ–π —Ä–∞–±–æ—Ç—ã –ø–æ –ø—Ä–µ–¥–æ–±—Ä–∞–±–æ—Ç–∫–µ –¥–∞–Ω–Ω—ã—Ö. –î–∞–≤–∞–π –±—É–¥–µ–º –æ–±—â–∞—Ç—å—Å—è –Ω–∞ **¬´—Ç—ã¬ª**. –ï—Å–ª–∏ —ç—Ç–æ –Ω–µ–ø—Ä–∏–µ–º–ª–µ–º–æ, –æ–±—è–∑–∞—Ç–µ–ª—å–Ω–æ –Ω–∞–ø–∏—à–∏ –º–Ω–µ –≤ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏—è—Ö ‚Äî –º—ã –ø–µ—Ä–µ–π–¥–µ–º –Ω–∞ **¬´–≤—ã¬ª**.

–¢—ã –ø—Ä–æ–¥–µ–ª–∞–ª–∞ –±–æ–ª—å—à—É—é —Ä–∞–±–æ—Ç—É –Ω–∞–¥ –ø—Ä–æ–µ–∫—Ç–æ–º, –æ–¥–Ω–∞–∫–æ –≤ –ª—é–±–æ–º –¥–µ–ª–µ –≤—Å–µ–≥–¥–∞ –º–æ–∂–Ω–æ –º–æ–∂–Ω–æ —á—Ç–æ-—Ç–æ —É–ª—É—á—à–∏—Ç—å. –ú–æ—è –æ—Å–Ω–æ–≤–Ω–∞—è —Ü–µ–ª—å ‚Äî –Ω–µ –ø–æ–∫–∞–∑–∞—Ç—å, —á—Ç–æ –≥–¥–µ-—Ç–æ —Å–æ–≤–µ—Ä—à–µ–Ω—ã –∫–∞–∫–∏–µ-–ª–∏–±–æ –æ—à–∏–±–∫–∏, –∞ –ø–æ–¥–µ–ª–∏—Ç—å—Å—è —Å–≤–æ–∏–º –æ–ø—ã—Ç–æ–º, –∫–æ—Ç–æ—Ä—ã–π –ø–æ–º–æ–∂–µ—Ç —Ç–µ–±–µ –≤ –¥–∞–ª—å–Ω–µ–π—à–∏—Ö —Ä–∞–±–æ—Ç–∞—Ö. –î–∞–ª–µ–µ –≤ —Ñ–∞–π–ª–µ —Ç—ã —Å–º–æ–∂–µ—à—å —É–≤–∏–¥–∏—Ç—å –º–æ–∏ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏, –ø–æ—Å—Ç–∞—Ä–∞–π—Å—è —É—á–µ—Å—Ç—å –∏—Ö –ø—Ä–∏ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏–∏ —Å–ª–µ–¥—É—é—â–∏—Ö –∑–∞–¥–∞–Ω–∏–π.    

–û–±—Ä–∞—Ç–∏ –≤–Ω–∏–º–∞–Ω–∏–µ –≤ –ø–µ—Ä–≤—É—é –æ—á–µ—Ä–µ–¥—å –Ω–∞ —Ç–µ, —á—Ç–æ –ø–æ–º–µ—á–∞–Ω—ã <span style="color:red">–∫—Ä–∞—Å–Ω—ã–º —Ü–≤–µ—Ç–æ–º</span>. –ü–æ—Å–ª–µ –∏—Ö –¥–æ—Ä–∞–±–æ—Ç–∫–∏ –ø—Ä–æ–µ–∫—Ç –±—É–¥–µ—Ç –ø—Ä–∏–Ω—è—Ç. <span style="color:green">–ó–µ–ª–µ–Ω—ã–º —Ü–≤–µ—Ç–æ–º</span> –æ—Ç–º–µ—á–µ–Ω—ã —É–¥–∞—á–Ω—ã–µ –∏ —ç–ª–µ–≥–∞–Ω—Ç–Ω—ã–µ —Ä–µ—à–µ–Ω–∏—è, –Ω–∞ –∫–æ—Ç–æ—Ä—ã–µ –º–æ–∂–Ω–æ –æ–ø–∏—Ä–∞—Ç—å—Å—è –≤ –±—É–¥—É—â–∏—Ö –ø—Ä–æ–µ–∫—Ç–∞—Ö. <span style="color:orange">–û—Ä–∞–Ω–∂–µ–≤—ã–º —Ü–≤–µ—Ç–æ–º</span> –≤—ã–¥–µ–ª–µ–Ω–æ —Ç–æ, —á—Ç–æ –≤ —Å–ª–µ–¥—É—é—â–∏–π —Ä–∞–∑ –º–æ–∂–Ω–æ —Å–¥–µ–ª–∞—Ç—å –ø–æ-–¥—Ä—É–≥–æ–º—É. –¢—ã –º–æ–∂–µ—à—å —É—á–µ—Å—Ç—å —ç—Ç–∏ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏ –ø—Ä–∏ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏–∏ –±—É–¥—É—â–∏—Ö –∑–∞–¥–∞–Ω–∏–π –∏–ª–∏ –¥–æ—Ä–∞–±–æ—Ç–∞—Ç—å –ø—Ä–æ–µ–∫—Ç —Å–µ–π—á–∞—Å (–æ–¥–Ω–∞–∫–æ —ç—Ç–æ –Ω–µ –æ–±—è–∑–∞—Ç–µ–ª—å–Ω–æ).

–î–∞–≤–∞–π —Ä–∞–±–æ—Ç–∞—Ç—å –Ω–∞–¥ –ø—Ä–æ–µ–∫—Ç–æ–º –≤ –¥–∏–∞–ª–æ–≥–µ: –µ—Å–ª–∏ —Ç—ã **—á—Ç–æ-—Ç–æ –º–µ–Ω—è–µ—à—å** –≤ –ø—Ä–æ–µ–∫—Ç–µ –ø–æ –º–æ–∏–º —Ä–µ–∫–æ–º–µ–Ω–¥–∞—Ü–∏—è–º ‚Äî **–ø–∏—à–∏ –æ–± —ç—Ç–æ–º**. –í—ã–±–µ—Ä–∏ –¥–ª—è —Å–≤–æ–∏—Ö –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤ –∫–∞–∫–æ–π-—Ç–æ –∑–∞–º–µ—Ç–Ω—ã–π —Ü–≤–µ—Ç, —Ç–∞–∫ –º–Ω–µ –±—É–¥–µ—Ç –ª–µ–≥—á–µ –æ—Ç—Å–ª–µ–¥–∏—Ç—å –∏–∑–º–µ–Ω–µ–Ω–∏—è. –ü–æ–∂–∞–ª—É–π—Å—Ç–∞, **–Ω–µ –ø–µ—Ä–µ–º–µ—â–∞–π, –Ω–µ –∏–∑–º–µ–Ω—è–π –∏ –Ω–µ —É–¥–∞–ª—è–π –º–æ–∏ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏**. –í—Å—ë —ç—Ç–æ –ø–æ–º–æ–∂–µ—Ç –≤—ã–ø–æ–ª–Ω–∏—Ç—å –ø–æ–≤—Ç–æ—Ä–Ω—É—é –ø—Ä–æ–≤–µ—Ä–∫—É —Ç–≤–æ–µ–≥–æ –ø—Ä–æ–µ–∫—Ç–∞ –æ–ø–µ—Ä–∞—Ç–∏–≤–Ω–µ–µ¬ª.

–í —Ü–µ–ª–æ–º —Ä–∞–±–æ—Ç–∞ —Ö–æ—Ä–æ—à–∞—è, –≤–∏–¥–Ω–æ, —á—Ç–æ —Ç—ã —Å—Ç–∞—Ä–∞–ª–∞—Å—å. –î–æ—Ä–∞–±–∞—Ç—ã–≤–∞–π –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏ –∏ –æ—Ç–ø—Ä–∞–≤–ª—è–π —Ä–∞–±–æ—Ç—É –Ω–∞ –ø–æ–≤—Ç–æ—Ä–Ω–æ–µ —Ä–µ–≤—å—é, —è –±—É–¥—É –∂–¥–∞—Ç—å üòâ

</div>

<div style="border:solid PaleVioletRed 2px; padding: 20px">

<span style='color:black'> –ü—Ä–∏–≤–µ—Ç, –†—É—Å—Ç–∞–º! –ü—Ä–∏—è—Ç–Ω–æ –ø–æ–∑–Ω–∞–∫–æ–º–∏—Ç—å—Å—è. –°–ø–∞—Å–∏–±–æ –∑–∞ –±—ã—Å—Ç—Ä—É—é –ø—Ä–æ–≤–µ—Ä–∫—É, –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏ –∏ –ø–æ–¥–±–∞–¥—Ä–∏–≤–∞—é—â–∏–π —Ç–æ–Ω!
–Ø –≤—ã–±—Ä–∞–ª–∞ —Ä–æ–∑–æ–≤—ã–π —Ü–≤–µ—Ç –¥–ª—è —Å–≤–æ–∏—Ö –æ—Ç–≤–µ—Ç–æ–≤ (–Ω–∏–∫–∞–∫–∏—Ö –≥–µ–Ω–¥–µ—Ä–Ω—ã—Ö —Å—Ç–µ—Ä–µ–æ—Ç–∏–ø–æ–≤)!  </span>
</div>

<div class="alert alert-success">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ v2 </h2>

–°–ø–∞—Å–∏–±–æ, –∑–∞ –±—ã—Å—Ç—Ä—É—é –∏ –∫–∞—á–µ—Å—Ç–≤–µ–Ω–Ω—É—é –¥–æ—Ä–∞–±–æ—Ç–∫—É –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤! –í—Å–µ –º–æ–º–µ–Ω—Ç—ã –±—ã–ª–∏ –∏—Å–ø—Ä–∞–≤–ª–µ–Ω—ã, —Ç–∞–∫ —á—Ç–æ —Ä–∞–±–æ—Ç—É —è –ø—Ä–∏–Ω–∏–º–∞—é. –¢—ã –±–æ–ª—å—à–∞—è –º–æ–ª–æ–¥–µ—Ü, —á—Ç–æ –∏—Å–ø—Ä–∞–≤–∏–ª–∞ –≤—Å–µ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏ (–∏ –æ—Ä–∞–Ω–∂–µ–≤—ã–µ —Ç–æ–∂–µ). –ü—Ä–∏—è—Ç–Ω–æ –±—ã—Ç—å –ø–æ–ª–µ–∑–Ω—ã–º)
    
–í –æ–±—â–µ–º –ø–æ–ª—É—á–∏–ª–∞—Å—å –∫–ª–∞—Å—Å–Ω–∞—è —Ä–∞–±–æ—Ç–∞. –ë–ª–∞–≥–æ–¥–∞—Ä—é –∑–∞ —Å—Ç–∞—Ä–∞–Ω–∏—è –∏ –∏–Ω—Ç–µ—Ä–µ—Å –∏ –∂–µ–ª–∞—é —É—Å–ø–µ—Ö–æ–≤ –≤ –¥–∞–ª—å–Ω–µ–π—à–∏—Ö –ø—Ä–æ–µ–∫—Ç–∞—Ö üòä

</div>

## –ò—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏–µ –Ω–∞–¥—ë–∂–Ω–æ—Å—Ç–∏ –∑–∞—ë–º—â–∏–∫–æ–≤

–ó–∞–∫–∞–∑—á–∏–∫ ‚Äî –∫—Ä–µ–¥–∏—Ç–Ω—ã–π –æ—Ç–¥–µ–ª –±–∞–Ω–∫–∞. –ù—É–∂–Ω–æ —Ä–∞–∑–æ–±—Ä–∞—Ç—å—Å—è, –≤–ª–∏—è–µ—Ç –ª–∏ —Å–µ–º–µ–π–Ω–æ–µ –ø–æ–ª–æ–∂–µ–Ω–∏–µ –∏ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –¥–µ—Ç–µ–π –∫–ª–∏–µ–Ω—Ç–∞ –Ω–∞ —Ñ–∞–∫—Ç –ø–æ–≥–∞—à–µ–Ω–∏—è –∫—Ä–µ–¥–∏—Ç–∞ –≤ —Å—Ä–æ–∫. –í—Ö–æ–¥–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ –æ—Ç –±–∞–Ω–∫–∞ ‚Äî —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞ –æ –ø–ª–∞—Ç—ë–∂–µ—Å–ø–æ—Å–æ–±–Ω–æ—Å—Ç–∏ –∫–ª–∏–µ–Ω—Ç–æ–≤.

–†–µ–∑—É–ª—å—Ç–∞—Ç—ã –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è –±—É–¥—É—Ç —É—á—Ç–µ–Ω—ã –ø—Ä–∏ –ø–æ—Å—Ç—Ä–æ–µ–Ω–∏–∏ –º–æ–¥–µ–ª–∏ **–∫—Ä–µ–¥–∏—Ç–Ω–æ–≥–æ —Å–∫–æ—Ä–∏–Ω–≥–∞** ‚Äî —Å–ø–µ—Ü–∏–∞–ª—å–Ω–æ–π —Å–∏—Å—Ç–µ–º—ã, –∫–æ—Ç–æ—Ä–∞—è –æ—Ü–µ–Ω–∏–≤–∞–µ—Ç —Å–ø–æ—Å–æ–±–Ω–æ—Å—Ç—å –ø–æ—Ç–µ–Ω—Ü–∏–∞–ª—å–Ω–æ–≥–æ –∑–∞—ë–º—â–∏–∫–∞ –≤–µ—Ä–Ω—É—Ç—å –∫—Ä–µ–¥–∏—Ç –±–∞–Ω–∫—É.

### –®–∞–≥ 1. –û—Ç–∫—Ä–æ–π—Ç–µ —Ñ–∞–π–ª —Å –¥–∞–Ω–Ω—ã–º–∏ –∏ –∏–∑—É—á–∏—Ç–µ –æ–±—â—É—é –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é.

In [1]:
import pandas as pd #–ü—Ä–æ—á–∏—Ç–∞–µ–º —Ñ–∞–π–ª data.csv –∏ —Å–æ—Ö—Ä–∞–Ω–∏–º –µ–≥–æ –≤ –ø–µ—Ä–µ–º–µ–Ω–Ω–æ–π df.
df = pd.read_csv('/datasets/data.csv')

In [2]:
df.info()  #–ü–æ–ª—É—á–∏–º –æ–±—â—É—é –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ –¥–∞–Ω–Ω—ã—Ö —Ç–∞–±–ª–∏—Ü—ã –∏ –≤—ã–≤–µ–¥–µ–º –Ω–∞ —ç–∫—Ä–∞–Ω –ø–µ—Ä–≤—ã—Ö 10 —Å—Ç—Ä–æ–∫ —Ç–∞–±–ª–∏—Ü—ã.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
children            21525 non-null int64
days_employed       19351 non-null float64
dob_years           21525 non-null int64
education           21525 non-null object
education_id        21525 non-null int64
family_status       21525 non-null object
family_status_id    21525 non-null int64
gender              21525 non-null object
income_type         21525 non-null object
debt                21525 non-null int64
total_income        19351 non-null float64
purpose             21525 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB

In [3]:
display(df.head(10))

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,–≤—ã—Å—à–µ–µ,0,–∂–µ–Ω–∞—Ç / –∑–∞–º—É–∂–µ–º,0,F,—Å–æ—Ç—Ä—É–¥–Ω–∏–∫,0,253875.639453,–ø–æ–∫—É–ø–∫–∞ –∂–∏–ª—å—è
1,1,-4024.803754,36,—Å—Ä–µ–¥–Ω–µ–µ,1,–∂–µ–Ω–∞—Ç / –∑–∞–º—É–∂–µ–º,0,F,—Å–æ—Ç—Ä—É–¥–Ω–∏–∫,0,112080.014102,–ø—Ä–∏–æ–±—Ä–µ—Ç–µ–Ω–∏–µ –∞–≤—Ç–æ–º–æ–±–∏–ª—è
2,0,-5623.422610,33,–°—Ä–µ–¥–Ω–µ–µ,1,–∂–µ–Ω–∞—Ç / –∑–∞–º—É–∂–µ–º,0,M,—Å–æ—Ç—Ä—É–¥–Ω–∏–∫,0,145885.952297,–ø–æ–∫—É–ø–∫–∞ –∂–∏–ª—å—è
3,3,-4124.747207,32,—Å—Ä–µ–¥–Ω–µ–µ,1,–∂–µ–Ω–∞—Ç / –∑–∞–º—É–∂–µ–º,0,M,—Å–æ—Ç—Ä—É–¥–Ω–∏–∫,0,267628.550329,–¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ–µ –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ
4,0,340266.072047,53,—Å—Ä–µ–¥–Ω–µ–µ,1,–≥—Ä–∞–∂–¥–∞–Ω—Å–∫–∏–π –±—Ä–∞–∫,1,F,–ø–µ–Ω—Å–∏–æ–Ω–µ—Ä,0,158616.077870,—Å—ã–≥—Ä–∞—Ç—å —Å–≤–∞–¥—å–±—É
5,0,-926.185831,27,–≤—ã—Å—à–µ–µ,0,–≥—Ä–∞–∂–¥–∞–Ω—Å–∫–∏–π –±—Ä–∞–∫,1,M,–∫–æ–º–ø–∞–Ω—å–æ–Ω,0,255763.565419,–ø–æ–∫—É–ø–∫–∞ –∂–∏–ª—å—è
6,0,-2879.202052,43,–≤—ã—Å—à–µ–µ,0,–∂–µ–Ω–∞—Ç / –∑–∞–º—É–∂–µ–º,0,F,–∫–æ–º–ø–∞–Ω—å–æ–Ω,0,240525.971920,–æ–ø–µ—Ä–∞—Ü–∏–∏ —Å –∂–∏–ª—å–µ–º
7,0,-152.779569,50,–°–†–ï–î–ù–ï–ï,1,–∂–µ–Ω–∞—Ç / –∑–∞–º—É–∂–µ–º,0,M,—Å–æ—Ç—Ä—É–¥–Ω–∏–∫,0,135823.934197,–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ
8,2,-6929.865299,35,–í–´–°–®–ï–ï,0,–≥—Ä–∞–∂–¥–∞–Ω—Å–∫–∏–π –±—Ä–∞–∫,1,F,—Å–æ—Ç—Ä—É–¥–Ω–∏–∫,0,95856.832424,–Ω–∞ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏–µ —Å–≤–∞–¥—å–±—ã
9,0,-2188.756445,41,—Å—Ä–µ–¥–Ω–µ–µ,1,–∂–µ–Ω–∞—Ç / –∑–∞–º—É–∂–µ–º,0,M,—Å–æ—Ç—Ä—É–¥–Ω–∏–∫,0,144425.938277,–ø–æ–∫—É–ø–∫–∞ –∂–∏–ª—å—è –¥–ª—è —Å–µ–º—å–∏

<div class="alert alert-warning">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ </h2>

–°–æ–≤–µ—Ç –Ω–∞ –±—É–¥—É—â–µ–µ: –Ω–µ —É–≤–ª–µ–∫–∞–π—Å—è –º–∞—Å—Å–æ–≤—ã–º –≤—ã–≤–æ–¥–æ–º —á–µ—Ä–µ–∑ —Ñ—É–Ω–∫—Ü–∏—é `print`. –î–ª—è —Ç–∞–±–ª–∏—Ü –ª—É—á—à–µ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å –≤—Å—Ç—Ä–æ–µ–Ω–Ω—ã–µ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏ jupyter notebook (–ø—Ä–æ—Å—Ç–æ –≤—ã–∑—ã–≤–∞—è –∏–º—è –ø–µ—Ä–µ–º–µ–Ω–Ω–æ–π —Å –¥–∞—Ç–∞—Å–µ—Ç–æ–º), –ª–∏–±–æ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å —Ñ—É–Ω–∫—Ü–∏—é `display`. –ù–∞–ø—Ä–∏–º–µ—Ä —Ç–∞–∫:
    
`df.head()`
    
`display(df.info())`

</div>

<div style="border:solid PaleVioletRed 2px; padding: 20px"> –û—Ç–æ–±—Ä–∞–∂–µ–Ω–∏–µ —Ä–µ–∑—É–ª—å—Ç–∞—Ç–æ–≤ —Å –ø–æ–º–æ—â—å—é —Ñ—É–Ω–∫—Ü–∏–∏ display –¥–µ–π—Å—Ç–≤–∏—Ç–µ–ª—å–Ω–æ —É–¥–æ–±–Ω–µ–µ. –°–ø–∞—Å–∏–±–æ!  </div>

–í—Å–µ–≥–æ –≤ —Ç–∞–±–ª–∏—Ü–µ 12 —Å—Ç–æ–ª–±—Ü–æ–≤ (–ø—Ä–∏–∑–Ω–∞–∫–æ–≤) –∏ 21525 —Ä—è–¥–æ–≤ (–¥–∞–Ω–Ω—ã—Ö –æ –∫–ª–∏–µ–Ω—Ç–∞—Ö). 

–†–∞–∑–±–µ—Ä—ë–º, –∫–∞–∫–∏–µ –≤ df —Å—Ç–æ–ª–±—Ü—ã –∏ –∫–∞–∫—É—é –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ–Ω–∏ —Å–æ–¥–µ—Ä–∂–∞—Ç:

- children ‚Äî –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –¥–µ—Ç–µ–π –≤ —Å–µ–º—å–µ - –∫–æ–ª–∏—á–µ—Å—Ç–≤–µ–Ω–Ω–∞—è –ø–µ—Ä–µ–º–µ–Ω–Ω–∞—è - —Ü–µ–ª–æ–µ —á–∏—Å–ª–æ
- days_employed ‚Äî –æ–±—â–∏–π —Ç—Ä—É–¥–æ–≤–æ–π —Å—Ç–∞–∂ –≤ –¥–Ω—è—Ö - –∫–æ–ª–∏—á–µ—Å—Ç–≤–µ–Ω–Ω–∞—è –ø–µ—Ä–µ–º–µ–Ω–Ω–∞—è - —á–∏—Å–ª–æ —Å –ø–ª–∞–≤–∞—é—â–µ–π —Ç–æ—á–∫–æ–π
- dob_years ‚Äî –≤–æ–∑—Ä–∞—Å—Ç –∫–ª–∏–µ–Ω—Ç–∞ –≤ –≥–æ–¥–∞—Ö - –∫–æ–ª–∏—á–µ—Å—Ç–≤–µ–Ω–Ω–∞—è –ø–µ—Ä–µ–º–µ–Ω–Ω–∞—è - —Ü–µ–ª–æ–µ —á–∏—Å–ª–æ
- education ‚Äî —É—Ä–æ–≤–µ–Ω—å –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏—è –∫–ª–∏–µ–Ω—Ç–∞ -–∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω–∞—è –ø–µ—Ä–µ–º–µ–Ω–Ω–∞—è -  –æ–±—ä–µ–∫—Ç
- education_id ‚Äî –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —É—Ä–æ–≤–Ω—è –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏—è - —Ü–µ–ª–æ–µ —á–∏—Å–ª–æ
- family_status ‚Äî —Å–µ–º–µ–π–Ω–æ–µ –ø–æ–ª–æ–∂–µ–Ω–∏–µ  - –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω–∞—è –ø–µ—Ä–µ–º–µ–Ω–Ω–∞—è - –æ–±—ä–µ–∫—Ç
- family_status_id ‚Äî –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ–º–µ–π–Ω–æ–≥–æ –ø–æ–ª–æ–∂–µ–Ω–∏—è  - –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω–∞—è –ø–µ—Ä–µ–º–µ–Ω–Ω–∞—è -  —Ü–µ–ª–æ–µ —á–∏—Å–ª–æ
- gender ‚Äî –ø–æ–ª –∫–ª–∏–µ–Ω—Ç–∞  -–∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω–∞—è –ø–µ—Ä–µ–º–µ–Ω–Ω–∞—è - –æ–±—ä–µ–∫—Ç
- income_type ‚Äî —Ç–∏–ø –∑–∞–Ω—è—Ç–æ—Å—Ç–∏  -–∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω–∞—è –ø–µ—Ä–µ–º–µ–Ω–Ω–∞—è -  –æ–±—ä–µ–∫—Ç
- debt ‚Äî –∏–º–µ–ª –ª–∏ –∑–∞–¥–æ–ª–∂–µ–Ω–Ω–æ—Å—Ç—å –ø–æ –≤–æ–∑–≤—Ä–∞—Ç—É –∫—Ä–µ–¥–∏—Ç–æ–≤ - –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω–∞—è –ø–µ—Ä–µ–º–µ–Ω–Ω–Ω–∞—è -—Ü–µ–ª–æ–µ —á–∏—Å–ª–æ
- total_income ‚Äî –µ–∂–µ–º–µ—Å—è—á–Ω—ã–π –¥–æ—Ö–æ–¥ -  –∫–æ–ª–∏—á–µ—Å—Ç–≤–µ–Ω–Ω–∞—è –ø–µ—Ä–µ–º–µ–Ω–Ω–∞—è - —á–∏—Å–ª–æ —Å –ø–ª–∞–≤–∞—é—â–µ–π —Ç–æ—á–∫–æ–π
- purpose ‚Äî —Ü–µ–ª—å –ø–æ–ª—É—á–µ–Ω–∏—è –∫—Ä–µ–¥–∏—Ç–∞  - –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω–∞—è –ø–µ—Ä–µ–º–µ–Ω–Ω–∞—è - –æ–±—ä–µ–∫—Ç

–ü–æ—á—Ç–∏ –≤—Å–µ —Å—Ç–æ–ª–±—Ü—ã –Ω–µ —Å–æ–¥–µ—Ä–∂–∞—Ç –ø—Ä–æ–ø—É—Å–∫–æ–≤, –∑–∞ –∏—Å–∫–ª—é—á–µ–Ω–∏–µ–º –¥–≤—É—Ö days_employed –∏ total_income. 

–†–∞—Å—Å–º–æ—Ç—Ä–∏–º –∫–æ–ª–∏—á–µ—Å—Ç–≤–µ–Ω–Ω—ã–µ –ø–µ—Ä–µ–º–µ–Ω–Ω—ã–µ –±–æ–ª–µ–µ –ø–æ–¥—Ä–æ–±–Ω–æ.

In [4]:
df.describe()

,children,days_employed,dob_years,education_id,family_status_id,debt,total_income
count,21525.000000,19351.000000,21525.000000,21525.000000,21525.000000,21525.000000,1.935100e+04
mean,0.538908,63046.497661,43.293380,0.817236,0.972544,0.080883,1.674223e+05
std,1.381587,140827.311974,12.574584,0.548138,1.420324,0.272661,1.029716e+05
min,-1.000000,-18388.949901,0.000000,0.000000,0.000000,0.000000,2.066726e+04
25%,0.000000,-2747.423625,33.000000,1.000000,0.000000,0.000000,1.030532e+05
50%,0.000000,-1203.369529,42.000000,1.000000,0.000000,0.000000,1.450179e+05
75%,1.000000,-291.095954,53.000000,1.000000,1.000000,0.000000,2.034351e+05
max,20.000000,401755.400475,75.000000,4.000000,4.000000,1.000000,2.265604e+06

–ú–∏–Ω–∏–º–∞–ª—å–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –¥–ª—è —Å—Ç–æ–ª–±—Ü–æ–≤ children –∏ days_employed –æ—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω–æ–µ, —Å–∫–æ—Ä–µ–µ –≤—Å–µ–≥–æ —ç—Ç–æ –æ—à–∏–±–∫–∞.

–¢–µ–ø–µ—Ä—å –ø–æ—Å–º–æ—Ç—Ä–∏–º –Ω–∞ –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–µ –ø–µ—Ä–µ–º–µ–Ω–Ω—ã–µ.

In [38]:
def check_unique(data):
    print(data.name, ":",  data.unique())  #–º–µ—Ç–æ–¥ unique –ø–æ–∑–≤–æ–ª–∏—Ç –Ω–∞–º —É–≤–∏–¥–µ—Ç—å —Å–ø–∏—Å–æ–∫ –≤—Å–µ—Ö –≤–∞—Ä–∏–∞–Ω—Ç–æ–≤ –¥–ª—è –ø–µ—Ä–µ–º–µ–Ω–Ω–æ–π

cat_var = [df['education'],df['children'],df['gender'],df['family_status'],df['income_type'],df['purpose'],df['debt']]  


for var in cat_var:
    display(check_unique(var))

education : ['–≤—ã—Å—à–µ–µ' '—Å—Ä–µ–¥–Ω–µ–µ' '–Ω–µ–æ–∫–æ–Ω—á–µ–Ω–Ω–æ–µ –≤—ã—Å—à–µ–µ' '–Ω–∞—á–∞–ª—å–Ω–æ–µ' '—É—á–µ–Ω–∞—è —Å—Ç–µ–ø–µ–Ω—å']

None

children : [1 0 3 2 4 5]

None

gender : ['F' 'M' 'XNA']

None

family_status : ['–∂–µ–Ω–∞—Ç / –∑–∞–º—É–∂–µ–º' '–≥—Ä–∞–∂–¥–∞–Ω—Å–∫–∏–π –±—Ä–∞–∫' '–≤–¥–æ–≤–µ—Ü / –≤–¥–æ–≤–∞' '–≤ —Ä–∞–∑–≤–æ–¥–µ'
 '–ù–µ –∂–µ–Ω–∞—Ç / –Ω–µ –∑–∞–º—É–∂–µ–º']

None

income_type : ['—Å–æ—Ç—Ä—É–¥–Ω–∏–∫' '–ø–µ–Ω—Å–∏–æ–Ω–µ—Ä' '–∫–æ–º–ø–∞–Ω—å–æ–Ω' '–≥–æ—Å—Å–ª—É–∂–∞—â–∏–π' '–±–µ–∑—Ä–∞–±–æ—Ç–Ω—ã–π'
 '–ø—Ä–µ–¥–ø—Ä–∏–Ω–∏–º–∞—Ç–µ–ª—å' '—Å—Ç—É–¥–µ–Ω—Ç' '–≤ –¥–µ–∫—Ä–µ—Ç–µ']

None

purpose : ['–ø–æ–∫—É–ø–∫–∞ –∂–∏–ª—å—è' '–ø—Ä–∏–æ–±—Ä–µ—Ç–µ–Ω–∏–µ –∞–≤—Ç–æ–º–æ–±–∏–ª—è' '–¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ–µ –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ'
 '—Å—ã–≥—Ä–∞—Ç—å —Å–≤–∞–¥—å–±—É' '–æ–ø–µ—Ä–∞—Ü–∏–∏ —Å –∂–∏–ª—å–µ–º' '–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ'
 '–Ω–∞ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏–µ —Å–≤–∞–¥—å–±—ã' '–ø–æ–∫—É–ø–∫–∞ –∂–∏–ª—å—è –¥–ª—è —Å–µ–º—å–∏' '–ø–æ–∫—É–ø–∫–∞ –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç–∏'
 '–ø–æ–∫—É–ø–∫–∞ –∫–æ–º–º–µ—Ä—á–µ—Å–∫–æ–π –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç–∏' '–ø–æ–∫—É–ø–∫–∞ –∂–∏–ª–æ–π –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç–∏'
 '—Å—Ç—Ä–æ–∏—Ç–µ–ª—å—Å—Ç–≤–æ —Å–æ–±—Å—Ç–≤–µ–Ω–Ω–æ–π –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç–∏' '–Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç—å'
 '—Å—Ç—Ä–æ–∏—Ç–µ–ª—å—Å—Ç–≤–æ –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç–∏' '–Ω–∞ –ø–æ–∫—É–ø–∫—É –ø–æ–¥–µ—Ä–∂–∞–Ω–Ω–æ–≥–æ –∞–≤—Ç–æ–º–æ–±–∏–ª—è'
 '–Ω–∞ –ø–æ–∫—É–ø–∫—É —Å–≤–æ–µ–≥–æ –∞–≤—Ç–æ–º–æ–±–∏–ª—è' '–æ–ø–µ—Ä–∞—Ü–∏–∏ —Å –∫–æ–º–º–µ—Ä—á–µ—Å–∫–æ–π –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç—å—é'
 '—Å—Ç—Ä–æ–∏—Ç–µ–ª—å—Å—Ç–≤–æ –∂–∏–ª–æ–π –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç–∏' '–∂–∏–ª—å–µ'
 '–æ–ø–µ—Ä–∞—Ü–∏–∏ —Å–æ —Å–≤–æ–µ–π –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç—å—é' '–∞–≤—Ç–æ–º–æ–±–∏–ª–∏' '–∑–∞–Ω—è—Ç—å—Å—è –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ–º'
 '—Å–¥–µ–ª–∫–∞ —Å –ø–æ–¥–µ—Ä–∂–∞–Ω–Ω—ã–º –∞–≤—Ç–æ–º–æ–±–∏–ª–µ–º' '–ø–æ–ª—É—á–µ–Ω–∏–µ –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏—è' '–∞–≤—Ç–æ–º–æ–±–∏–ª—å'
 '—Å–≤–∞–¥—å–±–∞' '–ø–æ–ª—É—á–µ–Ω–∏–µ –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ–≥–æ –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏—è' '–ø–æ–∫—É–ø–∫–∞ —Å–≤–æ–µ–≥–æ –∂–∏–ª—å—è'
 '–æ–ø–µ—Ä–∞—Ü–∏–∏ —Å –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç—å—é' '–ø–æ–ª—É—á–µ–Ω–∏–µ –≤—ã—Å—à–µ–≥–æ –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏—è'
 '—Å–≤–æ–π –∞–≤—Ç–æ–º–æ–±–∏–ª—å' '—Å–¥–µ–ª–∫–∞ —Å –∞–≤—Ç–æ–º–æ–±–∏–ª–µ–º' '–ø—Ä–æ—Ñ–∏–ª—å–Ω–æ–µ –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ'
 '–≤—ã—Å—à–µ–µ –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ' '–ø–æ–∫—É–ø–∫–∞ –∂–∏–ª—å—è –¥–ª—è —Å–¥–∞—á–∏' '–Ω–∞ –ø–æ–∫—É–ø–∫—É –∞–≤—Ç–æ–º–æ–±–∏–ª—è'
 '—Ä–µ–º–æ–Ω—Ç –∂–∏–ª—å—é' '–∑–∞–Ω—è—Ç—å—Å—è –≤—ã—Å—à–∏–º –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ–º']

None

debt : [0 1]

None

<div class="alert alert-warning">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ </h2>

–ó–¥–µ—Å—å —Ç—ã –ø–æ–≤—Ç–æ—Ä—è–µ—à—å –æ–¥–Ω–æ –∏ —Ç–æ –∂–µ –¥–µ–π—Å—Ç–≤–∏–µ –Ω–µ—Å–∫–æ–ª—å–∫–æ —Ä–∞–∑, –≤–æ–∑–º–æ–∂–Ω–æ —Ç–æ–≥–¥–∞ —Å—Ç–æ–∏—Ç –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å –¥–ª—è —ç—Ç–æ–≥–æ —Ü–∏–∫–ª—ã, –ª–∏–±–æ –Ω–∞–ø–∏—Å–∞—Ç—å –¥–ª—è —ç—Ç–æ–≥–æ –æ—Ç–¥–µ–ª—å–Ω—É—é —Ñ—É–Ω–∫—Ü–∏—é ü§î

</div>

<div style="border:solid PaleVioletRed 2px; padding: 20px">
–î–æ–±–∞–≤–∏–ª–∞ –∏ —Ñ—É–Ω–∫—Ü–∏—é, –∏ —Ü–∏–∫–ª.
–ü–æ—è–≤–∏–ª–∞—Å—å —Å—Ç—Ä–æ–∫–∞ —Å None. –û—Ç–∫—É–¥–∞ –æ–Ω–∞ —è –Ω–µ –∑–Ω–∞—é. –£–±—Ä–∞—Ç—å –Ω–µ –ø–æ–ª—É—á–∞–µ—Ç—Å—è.

<div class="alert alert-success">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ v2 </h2>

–û—Ç–ª–∏—á–Ω–∞—è —Ä–µ–∞–ª–∏–∑–∞—Ü–∏—è üëç None –≤—ã–ª–µ–∑–∞–µ—Ç, –ø–æ—Ç–æ–º—É —á—Ç–æ —Ç—ã –∏—Å–ø–æ–ª—å–∑–∞—É—à—å –∫–æ–º–±–∏–Ω–∞—Ü–∏—é `display` –∏ `print`. –ú–æ–∂–Ω–æ —É–±—Ä–∞—Ç—å `display`, –∞ –¥–ª—è —Ç–æ–≥–æ, —á—Ç–æ–±—ã –≤—ã–≤–æ–¥ —Ä–∞–∑–¥–µ–ª—è–ª—Å—è, –º–æ–∂–Ω–æ –≤ –ø—Ä–∏–Ω—Ç –¥–æ–±–∞–≤–∏—Ç—å `\n`. –í–æ—Ç —Ç–∞–∫ `print(data.name, ":",  data.unique(), '\n')`

</div>

### –í—ã–≤–æ–¥

–ö–∞–∂–¥–∞—è —Å—Ç—Ä–æ–∫–∞ —Ç–∞–±–ª–∏—Ü—ã —Å–æ–¥–µ—Ä–∂–∏—Ç –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ –∑–∞–µ–º—â–∏–∫–∞—Ö –±–∞–Ω–∫–∞. –ù–∞—à–∞ –∑–∞–¥–∞—á–∞ –≤—ã—è—Å–Ω–∏—Ç—å, –∫–∞–∫ —Å–µ–º–µ–π–Ω—ã–π —Å—Ç–∞—Ç—É—Å –∏ –Ω–∞–ª–∏—á–∏–µ –¥–µ—Ç–µ–π –≤–ª–∏—è–µ—Ç –Ω–∞ –ø–ª–∞—Ç–µ–∂–µ—Å–ø–æ—Å–æ–±–Ω–æ—Å—Ç—å –∑–∞–µ–º—â–∏–∫–∞. –û—Å–æ–±—ã–π –∏–Ω—Ç–µ—Ä–µ—Å –¥–ª—è –Ω–∞—Å –ø—Ä–µ–¥—Å—Ç–∞–≤–ª—è—é—Ç —Å—Ç–æ–ª–±—Ü—ã family_status, children, debt.

–î–ª—è –Ω–∞—á–∞–ª–∞ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –ø–æ–¥–≥–æ—Ç–æ–≤–∏—Ç—å –¥–∞–Ω–Ω—ã–µ –¥–ª—è –∞–Ω–∞–ª–∏–∑–∞. –£–∂–µ –≤–∏–¥–Ω–æ, —á—Ç–æ –Ω–µ–∫–æ—Ç–æ—Ä—ã–µ –ø–µ—Ä–µ–º–µ–Ω–Ω—ã–µ —Å–æ–¥–µ—Ä–∂–∞—Ç –æ—à–∏–±–∫–∏. –ù–∞–ø—Ä–∏–º–µ—Ä, –≤ –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–∏ –æ –¥–µ—Ç—è—Ö –µ—Å—Ç—å –æ—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –∏ –∑–Ω–∞—á–µ–Ω–∏–µ 20 (–ª–∏–±–æ —ç—Ç–æ –æ—á–µ–Ω—å –º–Ω–æ–≥–æ–¥–µ—Ç–Ω–∞—è —Å–µ–º—å—è, –ª–∏–±–æ –æ–ø–µ—á–∞—Ç–∫–∞). –°–∫–æ—Ä–µ–µ –≤—Å–µ–≥–æ –≤ –¥–∞–Ω–Ω—ã—Ö –µ—Å—Ç—å –¥—É–±–ª–∏–∫–∞—Ç—ã. –£–∂–µ —Å–µ–π—á–∞—Å –º—ã –∑–Ω–∞–µ–º, —á—Ç–æ –æ–¥–∏–Ω–∞–∫–æ–≤–æ–µ –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ –∑–∞–ø–∏—Å–∞–Ω–æ –≤ –ø–æ-—Ä–∞–∑–Ω–æ–º—É. 

–í —Å—Ç–æ–ª–±—Ü–µ —Å —Ü–µ–ª—å—é –∫—Ä–µ–¥–∏—Ç–∞ –º–Ω–æ–≥–æ –∑–Ω–∞—á–µ–Ω–∏–π, –Ω–æ –Ω–µ–∫–æ—Ç–æ—Ä—ã–µ –∏–∑ –Ω–∏—Ö –æ–ø–∏—Å—ã–≤–∞—é—Ç –æ–¥–Ω—É –∏ —Ç—É –∂–µ —Ü–µ–ª—å –æ–¥–∏–Ω–∞–∫–æ–≤—ã–º–∏ —Å–ª–æ–≤–∞–º–∏. –¢–∞–∫–∏–µ –ø–æ–≤—Ç–æ—Ä—ã –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ —É–±—Ä–∞—Ç—å –∏ –≤—ã–¥–µ–ª–∏—Ç—å —Å—Ö–æ–∂–∏–µ —Ü–µ–ª–∏.

### –®–∞–≥ 2. –ü—Ä–µ–¥–æ–±—Ä–∞–±–æ—Ç–∫–∞ –¥–∞–Ω–Ω—ã—Ö

–ò—Å–∫–ª—é—á–∏–º –ø—Ä–æ–ø—É—Å–∫–∏ –∏ –ø—Ä–æ–≤–µ—Ä–∏–º –¥–∞–Ω–Ω—ã–µ –Ω–∞ –Ω–∞–ª–∏—á–∏–µ –¥—É–±–ª–∏–∫–∞—Ç–æ–≤.

### –û–±—Ä–∞–±–æ—Ç–∫–∞ –ø—Ä–æ–ø—É—Å–∫–æ–≤

In [6]:
print(df.isna().sum()) #–ø—Ä–æ–≤–µ—Ä—è–µ–º –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤ –≤—ã–∑–æ–≤–æ–º –Ω–∞–±–æ—Ä–∞ –º–µ—Ç–æ–¥–æ–≤ –¥–ª—è —Å—É–º–º–∏—Ä–æ–≤–∞–Ω–∏—è –ø—Ä–æ–ø—É—â–µ–Ω–Ω—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π.

children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

–ü—É—Å—Ç—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è —Å–≤–∏–¥–µ—Ç–µ–ª—å—Å—Ç–≤—É—é—Ç, —á—Ç–æ —É –Ω–µ–∫–æ—Ç–æ—Ä—ã—Ö –∫–ª–∏–µ–Ω—Ç–æ–≤ –∑–∞—Ñ–∏–∫—Å–∏—Ä–æ–≤–∞–Ω–∞ –Ω–µ –≤—Å—è –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è. –û—Ç—Å—É—Ç—Å–≤—É—é—Ç –¥–∞–Ω–Ω—ã–µ –æ –∑–∞—Ä–ø–ª–∞—Ç–µ –∏ –æ —Ç—Ä—É–¥–æ–≤–æ–º —Å—Ç–∞–∂–µ.  –ü—Ä–∏—á–∏–Ω—ã –º–æ–≥—É—Ç –±—ã—Ç—å —Ä–∞–∑–Ω—ã–µ: –∑–∞–µ–º—â–∏–∫ —è–≤–ª—è–ª—Å—è –±–µ–∑—Ä–∞–±–æ—Ç–Ω—ã–º, –µ–≥–æ –Ω–µ —Å–ø—Ä–æ—Å–∏–ª–∏ –æ–± —ç—Ç–æ–º –∏–ª–∏ –æ–Ω —Å–∫—Ä—ã–ª —ç—Ç–∏ –¥–∞–Ω–Ω—ã–µ –Ω–∞–º–µ—Ä–µ–Ω–Ω–æ. 

–õ—é–¥–∏ —á–∞—Å—Ç–æ –Ω–µ –æ—Ç–≤–µ—á–∞—é—Ç –Ω–∞ –≤–æ–ø—Ä–æ—Å –æ —Å–≤–æ–∏—Ö –¥–æ—Ö–æ–¥–∞—Ö. –û–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ —Å–∏–ª—å–Ω–æ –∫–æ—Ä—Ä–µ–ª–∏—Ä—É–µ—Ç —Å –¥–æ—Ö–æ–¥–∞–º–∏, –∑–Ω–∞—á–∏—Ç –ø—Ä–æ–ø—É—Å–∫–∏ –≤ –ø–æ–ª–µ –¥–æ—Ö–æ–¥—ã –Ω–µ–ª—å–∑—è —Å—á–∏—Ç–∞—Ç—å —Å–æ–≤–µ—Ä—à–µ–Ω–Ω–æ —Å–ª—É—á–∞–π–Ω—ã–º–∏. –í—ã–ø–æ–ª–Ω—è–µ—Ç—Å—è –≥–∏–ø–æ—Ç–µ–∑–∞ MAR. MAR (Missing At Random) ‚Äî –¥–∞–Ω–Ω—ã–µ –ø—Ä–æ–ø—É—â–µ–Ω—ã –Ω–µ —Å–ª—É—á–∞–π–Ω–æ, –∞ –≤–≤–∏–¥—É –Ω–µ–∫–æ—Ç–æ—Ä—ã—Ö –∑–∞–∫–æ–Ω–æ–º–µ—Ä–Ω–æ—Å—Ç–µ–π.  –í —Å–ª—É—á–∞–µ MAR –∏—Å–∫–ª—é—á–µ–Ω–∏–µ –ø—Ä–æ–ø—É—Å–∫–æ–≤ –≤–ø–æ–ª–Ω–µ –ø—Ä–∏–µ–º–ª–µ–º–æ.

–û–¥–Ω–∞–∫–æ, —É–¥–∞–ª–µ–Ω–∏–µ –ø–æ—á—Ç–∏ 10% –¥–∞–Ω–Ω—ã—Ö –ø—Ä–∏–≤–µ–¥–µ—Ç –∫ –Ω–µ–ø—Ä–∞–≤–∏–ª—å–Ω—ã–º –≤—ã–≤–æ–¥–∞–º. –ü—Ä–æ–ø—É—Å–∫–∏ –º–æ–∂–Ω–æ –∑–∞–ø–æ–ª–Ω–∏—Ç—å –ø—Ä–æ–ø—É—Å–∫–∏ –º–æ–∂–Ω–æ —Å—Ä–µ–¥–Ω–∏–º –∞—Ä–∏—Ñ–º–µ—Ç–∏—á–µ—Å–∫–∏–º –∏–ª–∏ –º–µ–¥–∏–∞–Ω–æ–π. –î–ª—è –¥–æ—Ö–æ–¥–∞ –±–æ–ª—å—à–µ –ø–æ–¥–æ–π–¥–µ—Ç –º–µ–¥–∏–∞–Ω–∞, –¥–ª—è —Å—Ç–∞–∂–∞ –º–æ–∂–Ω–æ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å —Å—Ä–µ–¥–Ω–µ–µ.

–ü—Ä–∏ –∏–∑—É—á–µ–Ω–∏–∏ –ø–µ—Ä–µ–º–µ–Ω–Ω—ã—Ö –º—ã –∑–∞–º–µ—Ç–∏–ª–∏ –æ—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –≤ —Å—Ç–æ–ª–±—Ü–µ days_employed, –∑–∞–º–µ–Ω–∏–º –∏—Ö –Ω–∞ –ø–æ–ª–æ–∂–∏—Ç–µ–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è —Å –ø–æ–º–æ—â—å—é –º–µ—Ç–æ–¥–∞ abs()

In [7]:
df['days_employed'] = df['days_employed'].abs() #–∑–∞–º–µ–Ω–∞ –æ—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω—ã—Ö —á–∏—Å–µ–ª –Ω–∞ –∞–±—Å–æ–ª—é—Ç–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ

<div style="border:solid PaleVioletRed 2px; padding: 20px">
–ó–∞–º–µ–Ω–∏–ª–∞ –æ—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –≤ —Å—Ç–æ–ª–±—Ü–µ days_employed. –°—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –¥–µ–π—Å—Ç–≤–∏—Ç–µ–ª—å–Ω–æ –ø–æ–º–µ–Ω—è–ª–æ—Å–±
</div>

<div class="alert alert-success">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ v2 </h2>

Excellent

</div>

In [8]:
mean_days_employed = df['days_employed'].mean() #—Ä–∞—Å—á–∏—Ç–∞–µ–º —Å—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –≤—ã–∑–æ–≤–æ–º –º–µ—Ç–æ–¥–∞ mean
print('–°—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ —Ç—Ä—É–¥–æ–≤–æ–≥–æ —Å—Ç–∞–∂–∞, –≤ –¥–Ω—è—Ö: {}'.format(int(mean_days_employed)))

median_total_income = df['total_income'].median() #—Ä–∞—Å—á–∏—Ç–∞–µ–º –º–µ–¥–∏–∞–Ω–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –≤—ã–∑–æ–≤–æ–º –º–µ—Ç–æ–¥–∞ median
print('–ú–µ–¥–∏–∞–Ω–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –¥–æ—Ö–æ–¥–∞: {}'.format(int(median_total_income)))

df['days_employed']= df['days_employed'].fillna(mean_days_employed) #–∑–∞–ø–æ–ª–Ω–∏–º –ø—Ä–æ–ø—É—Å–∫–∏ –≤ —Å—Ç–æ–ª–±—Ü–µ days_employed —Å—Ä–µ–¥–Ω–∏–º –∑–Ω–∞—á–µ–Ω–∏–µ–º —Ç—Ä—É–¥–æ–≤–æ–≥–æ —Å—Ç–∞–∂–∞ –¥–ª—è –Ω–∞—à–µ–π –≤—ã–±–æ—Ä–∫–∏
df['total_income']= df['total_income'].fillna(median_total_income) #–ø—Ä–æ–ø—É—Å–∫–∏ –≤ —Å—Ç–æ–ª–±—Ü–µ total_income –∑–∞–º–µ–Ω–∏–º –º–µ–¥–∏–∞–Ω–Ω—ã–º –∑–Ω–∞—á–µ–Ω–∏–µ–º –¥–æ—Ö–æ–¥–∞
print(df.isna().sum()) #–ø—Ä–æ–≤–µ—Ä—è–µ–º –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤ —Ç–µ–ø–µ—Ä—å

–°—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ —Ç—Ä—É–¥–æ–≤–æ–≥–æ —Å—Ç–∞–∂–∞, –≤ –¥–Ω—è—Ö: 66914
–ú–µ–¥–∏–∞–Ω–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –¥–æ—Ö–æ–¥–∞: 145017
children            0
days_employed       0
dob_years           0
education           0
education_id        0
family_status       0
family_status_id    0
gender              0
income_type         0
debt                0
total_income        0
purpose             0
dtype: int64

### –í—ã–≤–æ–¥

–¢–µ–ø–µ—Ä—å –Ω–∞—à –Ω–∞–±–æ—Ä –¥–∞–Ω–Ω—ã—Ö –Ω–µ —Å–æ–¥–µ—Ä–∂–∏—Ç –ø—Ä–æ–ø—É—Å–∫–æ–≤.

### –ó–∞–º–µ–Ω–∞ —Ç–∏–ø–∞ –¥–∞–Ω–Ω—ã—Ö

–î–ª—è —É–¥–æ–±—Å—Ç–≤–∞ –ø—Ä–∏–≤–µ–¥–µ–º –≤—Å–µ –∑–Ω–∞—á–µ–Ω–∏—è –∫ —Ü–µ–ª–æ–º—É —á–∏—Å–ª—É - –∫ —Ç–∏–ø—É int. –¢–∞–∫–∂–µ –∑–∞–º–µ–Ω–∏–º –æ—à–∏–±–æ—á–Ω—ã–µ –æ—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è

In [9]:

df['days_employed'] = df['days_employed'].astype('int') #–ø—Ä–∏–≤–µ–¥–µ–Ω–∏–µ –∫ —Ü–µ–ª–æ–º—É —á–∏—Å–ª—É
print(df['days_employed'])
df['total_income'] = df['total_income'].astype('int') #–ø—Ä–∏–≤–µ–¥–µ–Ω–∏–µ –∫ —Ü–µ–ª–æ–º—É —á–∏—Å–ª—É
print(df['total_income'])

print(df['children'].unique()) #—Å—Ä–µ–¥–∏ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö –µ—Å—Ç—å –∑–Ω–∞—á–µ–Ω–∏–µ -1, –º–æ–∂–Ω–æ –ø—Ä–µ–¥–ø–æ–ª–æ–∂–∏—Ç—å, —á—Ç–æ —ç—Ç–æ –æ–ø–µ—á–∞—Ç–∫–∞
df['children'] = df['children'].abs() #–∑–∞–º–µ–Ω–∞ –æ—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω—ã—Ö —á–∏—Å–µ–ª –Ω–∞ –∞–±—Å–æ–ª—é—Ç–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ
print(df['children'].unique())

0          8437
1          4024
2          5623
3          4124
4        340266
          ...
21520      4529
21521    343937
21522      2113
21523      3112
21524      1984
Name: days_employed, Length: 21525, dtype: int64
0        253875
1        112080
2        145885
3        267628
4        158616
          ...
21520    224791
21521    155999
21522     89672
21523    244093
21524     82047
Name: total_income, Length: 21525, dtype: int64
[ 1  0  3  2 -1  4 20  5]
[ 1  0  3  2  4 20  5]

<div class="alert alert-warning">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ </h2>

–í—Å–µ –ø—Ä–∞–≤–∏–ª—å–Ω–æ! –û–¥–Ω–∞–∫–æ, –∏—Å–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –æ—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π —è –±—ã –ø—Ä–æ–≤–µ–ª –¥–æ –∑–∞–º–µ–Ω—ã –ø—Ä–æ–ø—É—Å–∫–æ–≤, —Ç–∞–∫, —Å–∫–æ—Ä–µ–µ –≤—Å–µ–≥–æ, –∑–Ω–∞—á–µ–Ω–∏–µ `mean_days_employed` –ø–æ–º–µ–Ω—è–µ—Ç—Å—è

</div>

–ù–∞–ª–∏—á–∏–µ 20 –¥–µ—Ç–µ–π - —Ä–µ–¥–∫–æ—Å—Ç—å. –ú–æ–∂–Ω–æ –¥–æ–ø—É—Å—Ç–∏—Ç—å, —á—Ç–æ –≤ –æ–¥–∏–Ω –±–∞–Ω–∫ –º–æ–∂–µ—Ç –æ–±—Ä–∞—Ç–∏—Ç—å—Å—è –Ω–µ—Å–∫–æ–ª—å–∫–æ —Å–µ–º–µ–π —Å —Ä–æ–≤–Ω–æ 20 –¥–µ—Ç—å–º–∏. –ü—Ä–æ–≤–µ—Ä–∏–º, —Å–∫–æ–ª—å–∫–æ —Å—Ç—Ä–æ–∫ —Å–æ–¥–µ—Ä–∂–∞—Ç —Ç–∞–∫–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ.

In [10]:
print(df['children'].value_counts())

0     14149
1      4865
2      2055
3       330
20       76
4        41
5         9
Name: children, dtype: int64

–û–¥–Ω–∞ —Å–µ–º—å—è —Å 20 –¥–µ—Ç—å–º–∏ - –µ—â–µ –≤–æ–∑–º–æ–∂–Ω–æ, –Ω–µ—Å–∫–æ–ª—å–∫–æ —Å–µ–º–µ–π —Å 20 –¥–µ—Ç—å–º–∏ - —Ç–æ–∂–µ –≤–µ—Ä–æ—è—Ç–Ω–æ, 76 —Å–µ–º–µ–π - –ø–æ—Ö–æ–∂–µ –Ω–∞ –æ–ø–µ—á–∞—Ç–∫—É. –°–∫–æ—Ä–µ–µ, –≤—Å–µ–≥–æ —Ç–∞–º –ª–∏—à–Ω–∏–π –Ω–æ–ª—å. –ó–∞–º–µ–Ω–∏–º –Ω–∞ —á–∏—Å–ª–æ 2.

In [11]:

df.loc[df['children']==20, 'children']=2 
print(df['children'].value_counts())

0    14149
1     4865
2     2131
3      330
4       41
5        9
Name: children, dtype: int64

### –í—ã–≤–æ–¥

–¢–µ–ø–µ—Ä—å –≤ –¥–∞–Ω–Ω—ã—Ö –Ω–µ—Ç –æ–ø–µ—á–∞—Ç–æ–∫, –∫–æ—Ç–æ—Ä—ã–µ –º–æ–≥—É—Ç –∏—Å–∫–∞–∑–∏—Ç—å —Ä–µ–∑—É–ª—å—Ç–∞—Ç, –∞ —Ç–∞–∫–∂–µ –∏—Å–ø–æ–ª—å–∑—É—é—Ç—Å—è –±–æ–ª–µ–µ –ø–æ–¥—Ö–æ–¥—è—â–∏–µ –¥–ª—è –≤—ã—á–∏—Å–ª–µ–Ω–∏–π —Ç–∏–ø—ã –¥–∞–Ω–Ω—ã—Ö.

### –û–±—Ä–∞–±–æ—Ç–∫–∞ –¥—É–±–ª–∏–∫–∞—Ç–æ–≤

–°–Ω–∞—á–∞–ª–∞ —É–±–µ—Ä–µ–º —É–∂–µ –Ω–∞–π–¥–µ–Ω–Ω—ã–µ –ø–æ–≤—Ç–æ—Ä–µ–Ω–∏—è –≤ —Å—Ç–æ–ª–±—Ü–µ education. –û–¥–∏–Ω–∞–∫–æ–≤–æ–µ –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ –Ω–∞–ø–∏—Å–∞–Ω–æ –≤ —Ä–∞–∑–Ω—ã—Ö —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ö.

In [12]:
print(df['education'].value_counts())

—Å—Ä–µ–¥–Ω–µ–µ                13750
–≤—ã—Å—à–µ–µ                  4718
–°–†–ï–î–ù–ï–ï                  772
–°—Ä–µ–¥–Ω–µ–µ                  711
–Ω–µ–æ–∫–æ–Ω—á–µ–Ω–Ω–æ–µ –≤—ã—Å—à–µ–µ      668
–í–´–°–®–ï–ï                   274
–í—ã—Å—à–µ–µ                   268
–Ω–∞—á–∞–ª—å–Ω–æ–µ                250
–ù–µ–æ–∫–æ–Ω—á–µ–Ω–Ω–æ–µ –≤—ã—Å—à–µ–µ       47
–ù–ï–û–ö–û–ù–ß–ï–ù–ù–û–ï –í–´–°–®–ï–ï       29
–ù–ê–ß–ê–õ–¨–ù–û–ï                 17
–ù–∞—á–∞–ª—å–Ω–æ–µ                 15
—É—á–µ–Ω–∞—è —Å—Ç–µ–ø–µ–Ω—å             4
–£–ß–ï–ù–ê–Ø –°–¢–ï–ü–ï–ù–¨             1
–£—á–µ–Ω–∞—è —Å—Ç–µ–ø–µ–Ω—å             1
Name: education, dtype: int64

–ü—Ä–∏–≤–µ–¥–µ–º –≤—Å–µ –ø–µ—Ä–µ–º–µ–Ω–Ω—ã–µ –∫ –æ–¥–Ω–æ–º—É —Ä–µ–≥–∏—Å—Ç—Ä—É.

In [13]:
df['education'] = df['education'].str.lower()
print(df['education'].value_counts())

—Å—Ä–µ–¥–Ω–µ–µ                15233
–≤—ã—Å—à–µ–µ                  5260
–Ω–µ–æ–∫–æ–Ω—á–µ–Ω–Ω–æ–µ –≤—ã—Å—à–µ–µ      744
–Ω–∞—á–∞–ª—å–Ω–æ–µ                282
—É—á–µ–Ω–∞—è —Å—Ç–µ–ø–µ–Ω—å             6
Name: education, dtype: int64

–¢–µ–ø–µ—Ä—å –ø—Ä–æ–≤–µ—Ä–∏–º –Ω–∞–ª–∏—á–∏–µ –¥—É–±–ª–∏—Ä—É—é—â–∏—Ö —Å—Ç—Ä–æ–∫

In [14]:
print(df.duplicated().sum())  #–ø—Ä–æ–≤–µ—Ä—è–µ–º –∫–æ–ª-–≤–æ –ø–æ–≤—Ç–æ—Ä—è—é—â–∏—Ö—Å—è —Å—Ç—Ä–æ–∫
df = df.drop_duplicates().reset_index(drop=True)  #—É–¥–∞–ª—è–µ–º –¥—É–±–ª–∏–∫–∞—Ç—ã —Å —Å–æ—Ö—Ä–∞–Ω–µ–Ω–∏–µ–º –∏–Ω–¥–µ–∫—Å–æ–≤
print(df.duplicated().sum()) #–ø—Ä–æ–≤–µ—Ä—è–µ–º, —á—Ç–æ –¥—É–±–ª–∏–∫–∞—Ç–æ–≤ –Ω–µ –æ—Å—Ç–∞–ª–æ—Å—å

71
0

<div style="border:solid PaleVioletRed 2px; padding: 20px"> 
 –£–¥–∞–ª–µ–Ω–∏–µ –¥—É–±–ª–∏–∫–∞—Ç–æ–≤ –≤ —Å—Ç–æ–ª–±—Ü–µ –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏—è –ø–µ—Ä–µ–Ω–µ—Å–ª–∞ –≤–≤–µ—Ä—Ö. –ö–æ–ª–∏—á–µ—Å—Ç–≤–æ –¥—É–±–ª–∏–∫–∞—Ç–æ–≤ —É–≤–µ–ª–∏—á–∏–ª–æ—Å—å –ø–æ—á—Ç–∏ –Ω–∞ 20 —Å—Ç—Ä–æ–∫!

<div class="alert alert-warning">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ </h2>

–ó–¥–µ—Å—å —è –±—ã —Ç–∞–∫–∂–µ –ø—Ä–∏–≤–µ–¥–µ–Ω–∏–µ –∫ –Ω–∏–∂–Ω–µ–º—É —Ä–µ–≥–∏—Å—Ç—Ä—É –ø–µ—Ä–µ–Ω–µ—Å –≤—ã—à–µ, –ø–æ—Ç–æ–º—É —á—Ç–æ —ç—Ç–æ –º–æ–∂–µ—Ç –ø–æ–≤–ª–∏—è—Ç—å –Ω–∞ –∫–æ–ª-–≤–æ –¥—É–±–ª–∏–∫–∞—Ç–æ–≤

</div>

### –í—ã–≤–æ–¥

–î—É–±–ª–∏—Ä–æ–≤–∞–Ω–∏–µ –∑–Ω–∞—á–µ–Ω–∏–π –≤ —Å—Ç–æ–ª–±—Ü–µ –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ –º–æ–∂–µ—Ç –±—ã—Ç—å —Å–≤—è–∑–∞–Ω–æ —Å —Ç–µ–º, —á—Ç–æ –¥–∞–Ω–Ω—ã–µ –≤–≤–æ–¥—è—Ç —Ä–∞–∑–Ω—ã–µ –æ–ø–µ—Ä–∞—Ç–æ—Ä—ã, –∫—Ç–æ-—Ç–æ –ø—Ä–µ–¥–ø–æ—á–∏—Ç–∞–µ—Ç –ø–∏—Å–∞—Ç—å –≤—Å–µ –≤ –≤–µ—Ä—Ö–Ω–µ–º —Ä–µ–≥–∏—Å—Ç—Ä–µ, –∞ –∫—Ç–æ-—Ç–æ –Ω–∞–æ–±–æ—Ä–æ—Ç. –î—É–±–ª–∏–∫–∞—Ç—ã —Å—Ç—Ä–æ–∫ –º–æ–≥–ª–∏ –≤–æ–∑–Ω–∏–∫–Ω—É—Ç –∏–∑-–∑–∞ —Ç–µ—Ö–Ω–∏—á–µ—Å–∫–æ–≥–æ —Å–±–æ—è –∏–ª–∏ –∑–∞–¥—É–±–ª–∏—Ä–æ–≤–∞–Ω—ã –ø—Ä–∏ –ø–µ—Ä–µ–Ω–æ—Å–µ –¥–∞–Ω–Ω—ã—Ö –≤ –±–∞–∑—É.

### –õ–µ–º–º–∞—Ç–∏–∑–∞—Ü–∏—è

–î–ª—è –∞–Ω–∞–ª–∏–∑–∞ –Ω–∞–º –Ω—É–∂–Ω–æ –≤—ã—è—Å–Ω–∏—Ç—å, –∫–∞–∫–∏–µ —Å–∞–º—ã–µ –ø–æ–ø—É–ª—è—Ä–Ω—ã–µ —Ü–µ–ª–∏ –¥–ª—è –∫—Ä–µ–¥–∏—Ç–∞. –í —Å—ã—Ä–æ–º –≤–∏–¥–µ –∞–Ω–∞–ª–∏–∑–∏—Ä–æ–≤–∞—Ç—å —Å—Ç–æ–ª–±–µ—Ü purpose —Å–ª–æ–∂–Ω–æ: —Ü–µ–ª–∏ –∑–∞–ø–∏—Å–∞–Ω—ã –ø—Ä–æ–∏–∑–≤–æ–ª—å–Ω–æ. –ù–µ–æ–±—Ö–æ–¥–∏–º–æ –ø—Ä–∏–≤–µ—Å—Ç–∏ –∏—Ö –∫ –æ–¥–Ω–æ–º—É –≤–∏–¥—É.

In [15]:
print(len(df['purpose'].unique())) #–ø–æ—Å—á–∏—Ç–∞–µ–º —Å–∫–æ–ª—å–∫–æ –≤—Å–µ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö –∑–∞–ø–∏—Å–µ–π —Ü–µ–ª–µ–π –∫—Ä–µ–¥–∏—Ç–∞

38

In [16]:
purposes = df['purpose'].tolist()

–ò–∑–±–∞–≤–∏–º—Å—è –æ—Ç –æ–¥–∏–Ω–∞–∫–æ–≤—ã—Ö –ø–æ —Å–º—ã—Å–ª—É –¥—É–±–ª–∏–∫–∞—Ç–æ–≤ —Å –ø–æ–º–æ—â—å—é –ª–µ–º–º–∞—Ç–∏–∑–∞—Ü–∏–∏, —Ç–æ –µ—Å—Ç—å –ø—Ä–∏–≤–µ–¥–µ–º —Å–ª–æ–≤–∞ –∫ —Å–ª–æ–≤–∞—Ä–Ω–æ–π —Ñ–æ—Ä–º–µ

In [17]:

purposes = ' '.join(purposes)

#–∏–º–ø–æ—Ä—Ç–∏—Ä—É–µ–º –±–∏–±–ª–∏–æ—Ç–µ–∫—É —Å —Ñ—É–Ω–∫—Ü–∏–µ–π –ª–µ–º–º–∞—Ç–∏–∑–∞—Ü–∏–∏ –Ω–∞ —Ä—É—Å—Å–∫–æ–º —è–∑—ã–∫–µ 
from pymystem3 import Mystem
m = Mystem()
#–ø–µ—Ä–µ–¥–∞–µ–º —Ñ—É–Ω–∫—Ü–∏–∏ –≤ –∫–∞—á–µ—Å—Ç–≤–µ –∞—Ä–≥—É–º–µ–Ω—Ç–∞ - —Å–ø–∏—Å–æ–∫ —Ü–µ–ª–µ–π 
lemmas = m.lemmatize(purposes)


#–ø–æ–¥—á–∏—Ç–∞–µ–º —á–∏—Å–ª–æ —É–ø–æ–º–∏–Ω–∞–Ω–∏–π –ª–µ–º–º–∞—Ç–∏–∑–∏—Ä—É–µ–º—ã—Ö —Å–ª–æ–≤ 
from collections import Counter
print(Counter(lemmas))

Counter({' ': 55023, '–Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç—å': 6351, '–ø–æ–∫—É–ø–∫–∞': 5897, '–∂–∏–ª—å–µ': 4460, '–∞–≤—Ç–æ–º–æ–±–∏–ª—å': 4306, '–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ': 4013, '—Å': 2918, '–æ–ø–µ—Ä–∞—Ü–∏—è': 2604, '—Å–≤–∞–¥—å–±–∞': 2324, '—Å–≤–æ–π': 2230, '–Ω–∞': 2222, '—Å—Ç—Ä–æ–∏—Ç–µ–ª—å—Å—Ç–≤–æ': 1878, '–≤—ã—Å–æ–∫–∏–π': 1374, '–ø–æ–ª—É—á–µ–Ω–∏–µ': 1314, '–∫–æ–º–º–µ—Ä—á–µ—Å–∫–∏–π': 1311, '–¥–ª—è': 1289, '–∂–∏–ª–æ–π': 1230, '—Å–¥–µ–ª–∫–∞': 941, '–¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã–π': 906, '–∑–∞–Ω–∏–º–∞—Ç—å—Å—è': 904, '–ø–æ–¥–µ—Ä–∂–∞—Ç—å': 853, '–ø—Ä–æ–≤–µ–¥–µ–Ω–∏–µ': 768, '—Å—ã–≥—Ä–∞—Ç—å': 765, '—Å–¥–∞—á–∞': 651, '—Å–µ–º—å—è': 638, '—Å–æ–±—Å—Ç–≤–µ–Ω–Ω—ã–π': 635, '—Å–æ': 627, '—Ä–µ–º–æ–Ω—Ç': 607, '–ø—Ä–∏–æ–±—Ä–µ—Ç–µ–Ω–∏–µ': 461, '–ø—Ä–æ—Ñ–∏–ª—å–Ω—ã–π': 436, '–ø–æ–¥–µ—Ä–∂–∞–Ω–Ω—ã–π': 111, '\n': 1})

–î–æ–±–∞–≤–∏–º –≤ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º —Å—Ç–æ–ª–±–µ—Ü, –∫–æ—Ç–æ—Ä—ã–π –±—É–¥–µ—Ç —Å–æ–¥–µ—Ä–∂–∞—Ç—å —Å–æ–æ—Ç–≤–µ—Ç–≤—É—é—â—É—é —Å—Ç–æ–ª–±—Ü—É purpose –ª–µ–º–º—É

In [18]:
def lemmatize(col):
    return m.lemmatize(col)
                        
df['purpose_lemmas'] = df['purpose'].apply(lemmatize)                

print(df['purpose_lemmas'].head())

0                 [–ø–æ–∫—É–ø–∫–∞,  , –∂–∏–ª—å–µ, \n]
1       [–ø—Ä–∏–æ–±—Ä–µ—Ç–µ–Ω–∏–µ,  , –∞–≤—Ç–æ–º–æ–±–∏–ª—å, \n]
2                 [–ø–æ–∫—É–ø–∫–∞,  , –∂–∏–ª—å–µ, \n]
3    [–¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã–π,  , –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ, \n]
4               [—Å—ã–≥—Ä–∞—Ç—å,  , —Å–≤–∞–¥—å–±–∞, \n]
Name: purpose_lemmas, dtype: object

<div style="border:solid PaleVioletRed 2px; padding: 20px">
–¢–∞–∫ –ª–æ–≥–∏—á–Ω–µ–µ, –Ω–æ –æ —Ç–æ–º, —á—Ç–æ –º–Ω–µ –ø–æ–Ω–∞–¥–æ–±–∏—Ç—å—Å—è —Ç–∞–∫–æ–π —Å—Ç–æ–ª–±–µ—Ü —è –ø–æ–Ω—è–ª–∞ —Ç–æ–ª—å–∫–æ, –∫–æ–≥–¥–∞ –¥–æ—à–ª–∞ –¥–æ –≤–æ–ø—Ä–æ—Å–∞ –ø—Ä–æ –Ω–∞–ª–∏—á–∏–µ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏. 
    </div>

### –í—ã–≤–æ–¥

–°–∞–º–∞—è —á–∞—Å—Ç–∞—è —Ü–µ–ª—å –∫—Ä–µ–¥–∏—Ç–∞ - —ç—Ç–æ –ø—Ä–∏–æ–±—Ä–µ—Ç–µ–Ω–∏–µ –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç–∏ –∏ –∂–∏–ª—å—è, –Ω–∞ –≤—Ç–æ—Ä–æ–º –º–µ—Å—Ç–µ - –ø–æ–∫—É–ø–∫–∞ –∞–≤—Ç–æ–º–æ–±–∏–ª—è, –Ω–∞ —Ç—Ä–µ—Ç—å–µ–º - –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ. –ó–∞—Ç–µ–º –∏–¥—É—Ç –æ–ø–µ—Ä–∞—Ü–∏–∏ –∏ —Å–≤–∞–¥—å–±—ã.

### –ö–∞—Ç–µ–≥–æ—Ä–∏–∑–∞—Ü–∏—è –¥–∞–Ω–Ω—ã—Ö

–ù–∞—à–∞ –æ—Å–Ω–æ–≤–Ω–∞—è –∑–∞–¥–∞—á–∞ - –≤—ã—è—Å–Ω–∏—Ç—å, –≤–ª–∏—è–µ—Ç –ª–∏ —Å–µ–º–µ–π–Ω–æ–µ –ø–æ–ª–æ–∂–µ–Ω–∏–µ –∏ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –¥–µ—Ç–µ–π –∫–ª–∏–µ–Ω—Ç–∞ –Ω–∞ —Ñ–∞–∫—Ç –ø–æ–≥–∞—à–µ–Ω–∏—è –∫—Ä–µ–¥–∏—Ç–∞ –≤ —Å—Ä–æ–∫. –í—ã–¥–µ–ª–∏–º –∫–∞—Ç–µ–≥–æ—Ä–∏–∏ –¥–ª—è –∞–Ω–∞–ª–∏–∑–∞. 

–ö–∞—Ç–µ–≥–æ—Ä–∏–∏ –ø–æ –Ω–∞–ª–∏—á–∏—é –¥–µ—Ç–µ–π
- –µ—Å—Ç—å –¥–µ—Ç–∏ (1-2 —Ä–µ–±–µ–Ω–∫–∞)
- –º–Ω–æ–≥–æ–¥–µ—Ç–Ω—ã–µ (3 –∏ –±–æ–ª–µ–µ)
- –Ω–µ—Ç –¥–µ—Ç–µ–π (0)

–ö–∞—Ç–µ–≥–æ—Ä–∏–∏ –ø–æ —Å–µ–º–µ–π–Ω–æ–º—É –ø–æ–ª–æ–∂–µ–Ω–∏—é:
- —Å–æ—Å—Ç–æ–∏—Ç –≤ –±—Ä–∞–∫–µ (–æ—Ç–Ω–µ—Å–µ–º —Å—é–¥–∞ –∏ –≥—Ä–∞–∂–¥–∞–Ω—Å–∫–∏–π, –∏ –∑–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞–Ω–Ω—ã–π)
- –Ω–µ —Å–æ—Å—Ç–æ–∏—Ç –≤ –±—Ä–∞–∫–µ (–æ—Ç–Ω–µ—Å–µ–º —Å—é–¥–∞ –æ–¥–∏–Ω–æ–∫–∏—Ö, –≤–¥–æ–≤—Ü–æ–≤ –∏ –≤ —Ä–∞–∑–≤–æ–¥–µ)

In [19]:
#—Å–æ–∑–¥–∞–¥–∏–º —Ñ—É–Ω–∫—Ü–∏—é, –∫–æ—Ç–æ—Ä–∞—è –±—É–¥–µ—Ç –æ–ø—Ä–µ–¥–µ–ª—è—Ç—å –∫–∞—Ç–µ–≥–æ—Ä–∏—é –ø—Ä–∏ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏–∏ —É—Å–ª–æ–≤–∏—è

def children_category(kids):
    if kids == 0:
        return '–Ω–µ—Ç –¥–µ—Ç–µ–π'
    if kids >= 1 and kids <= 2:
        return '–µ—Å—Ç—å –¥–µ—Ç–∏'
    if kids >= 3:
        return '–º–Ω–æ–≥–æ–¥–µ—Ç–Ω—ã–µ'
#–¥–æ–±–∞–≤–∏–º –Ω–æ–≤—ã–π —Å—Ç–æ–ª–±–µ—Ü —Å –∫–∞—Ç–µ–≥–æ—Ä–∏—è–º–∏ children_category
df['children_category'] = df['children'].apply(children_category)

    

def marriage_status(family_status_id):
    if family_status_id in (0, 1):
        return '–≤ –±—Ä–∞–∫–µ'
    if family_status_id in (2,3,4):
        return '–Ω–µ –≤ –±—Ä–∞–∫–µ'
    #–¥–æ–±–∞–≤–∏–º –Ω–æ–≤—ã–π —Å—Ç–æ–ª–±–µ—Ü —Å –∫–∞—Ç–µ–≥–æ—Ä–∏–µ–π marriage_status

df['marriage_status'] = df['family_status_id'].apply(marriage_status)

print(df['marriage_status'].value_counts())
print(df['children_category'].value_counts())

–≤ –±—Ä–∞–∫–µ       16490
–Ω–µ –≤ –±—Ä–∞–∫–µ     4964
Name: marriage_status, dtype: int64
–Ω–µ—Ç –¥–µ—Ç–µ–π      14091
–µ—Å—Ç—å –¥–µ—Ç–∏       6983
–º–Ω–æ–≥–æ–¥–µ—Ç–Ω—ã–µ      380
Name: children_category, dtype: int64

–í—ã–¥–µ–ª–∏–º –∫–∞—Ç–µ–≥–æ—Ä–∏–∏ –ø–æ –¥–æ—Ö–æ–¥—É. –ü—Ä–∏ —Ä–∞–∑–±–∏–µ–Ω–∏–∏ –±—É–¥–µ–º –æ—Ä–∏–µ–Ω—Ç–∏—Ä–æ–≤–∞—Ç—å—Å—è –Ω–∞ –¥–∞–Ω–Ω—ã–µ –ø–æ –∑–∞—Ä–ø–ª–∞—Ç–µ –≤ –†–§. –°—Ä–µ–¥–Ω—è—è –∑–∞—Ä–ø–ª–∞—Ç–∞ –ø–æ —Å—Ç—Ä–∞–Ω–µ - 43 400 —Ä—É–±–ª–µ–π

In [20]:
print('max', df['total_income'].max())
print('min', df['total_income'].min())


def total_income_group(total_income):
    if total_income < 45000:
        return '–Ω–∏–∑–∫–∏–π –¥–æ—Ö–æ–¥'
    if total_income >= 45000 and total_income <= 80000:
        return '—Å—Ä–µ–¥–Ω–∏–π –¥–æ—Ö–æ–¥'
    if total_income > 80000  and total_income <= 150000:
        return '–≤—ã—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ'
    if total_income > 150000  and total_income <= 500000:
        return '–≤—ã—Å–æ–∫–∏–π'
    if total_income > 500000:
        return '–æ—á–µ–Ω—å –≤—ã—Å–æ–∫–∏–π'
#–¥–æ–±–∞–≤–∏–º –Ω–æ–≤—ã–π —Å—Ç–æ–ª–±–µ—Ü —Å –∫–∞—Ç–µ–≥–æ—Ä–∏–µ–π total_income_group
df['total_income_group'] = df['total_income'].apply(total_income_group)
df['total_income_group'].value_counts()

max 2265604
min 20667

–≤—ã—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ    9994
–≤—ã—Å–æ–∫–∏–π          8962
—Å—Ä–µ–¥–Ω–∏–π –¥–æ—Ö–æ–¥    2059
–æ—á–µ–Ω—å –≤—ã—Å–æ–∫–∏–π     222
–Ω–∏–∑–∫–∏–π –¥–æ—Ö–æ–¥      217
Name: total_income_group, dtype: int64

–í—ã–¥–µ–ª–∏–º –∫–∞—Ç–µ–≥–æ—Ä–∏–∏ –ø–æ —Ü–µ–ª—è–º

In [21]:
def category_purpose(lemmas):
    for word in lemmas:
        if '–∂–∏–ª—å–µ' in word:
            return '–∂–∏–ª—å–µ'
        elif '–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ' in word:
            return '–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ'
        elif '–Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç—å' in word:
            return '–Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç—å'
        elif '—Å–≤–∞–¥—å–±–∞' in word:
            return '—Å–≤–∞–¥—å–±–∞'
        elif '–∞–≤—Ç–æ–º–æ–±–∏–ª—å' in word:
            return '–∞–≤—Ç–æ–º–æ–±–∏–ª—å'
        elif '–æ–ø–µ—Ä–∞—Ü–∏—è' in word:
            return '–æ–ø–µ—Ä–∞—Ü–∏—è'
        
    
    
                
df['category_purpose'] = df['purpose_lemmas'].apply(category_purpose)                

print(df['category_purpose'].head())

0          –∂–∏–ª—å–µ
1     –∞–≤—Ç–æ–º–æ–±–∏–ª—å
2          –∂–∏–ª—å–µ
3    –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ
4        —Å–≤–∞–¥—å–±–∞
Name: category_purpose, dtype: object

<div class="alert alert-success">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ </h2>

–ö–∞—Ç–µ–≥–æ—Ä–∏–∑–∞—Ü–∏—è –≤—ã–ø–æ–ª–Ω–µ–Ω–∞ –Ω–∞ –æ—Ç–ª–∏—á–Ω–æ

</div>

### –í—ã–≤–æ–¥

–ó–∞ –∫—Ä–µ–¥–∏—Ç–æ–º –æ–±—Ä–∞—â–∞–ª–æ—Å—å –±–æ–ª—å—à–µ –ª—é–¥–µ–π, —Å–æ—Å—Ç–æ—è—â–∏—Ö –≤ –±—Ä–∞–∫–µ, —á–µ–º –æ–¥–∏–Ω–æ–∫–∏—Ö. –° –¥–µ—Ç—å–º–∏ –∫—Ä–µ–¥–∏—Ç –±—Ä–∞–ª–∏ —Ä–µ–∂–µ. –õ—é–¥–∏ —Å –Ω–∏–∑–∫–∏–º –¥–æ—Ö–æ–¥–æ–º –∏ —Å –æ—á–µ–Ω—å –≤—ã—Å–æ–∫–∏–º –¥–æ—Ö–æ–¥–æ–º –≤ –≤—ã–±–æ—Ä–∫–µ –ø—Ä–µ–¥—Å—Ç–∞–≤–ª–µ–Ω—ã –º–µ–Ω—å—à–µ. –ë–æ–ª—å—à–µ –≤—Å–µ–≥–æ –∑–∞–µ–º—â–∏–∫–æ–≤ —Å –≤—ã—Å–æ–∫–∏–º –∏ —Å –¥–æ—Ö–æ–¥–æ–º –≤—ã—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ.

### –®–∞–≥ 3. –û—Ç–≤–µ—Ç—å—Ç–µ –Ω–∞ –≤–æ–ø—Ä–æ—Å—ã

- –ï—Å—Ç—å –ª–∏ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç—å –º–µ–∂–¥—É –Ω–∞–ª–∏—á–∏–µ–º –¥–µ—Ç–µ–π –∏ –≤–æ–∑–≤—Ä–∞—Ç–æ–º –∫—Ä–µ–¥–∏—Ç–∞ –≤ —Å—Ä–æ–∫?

In [22]:
children_debt = df.pivot_table(index = ['children_category', 'debt'], values = 'children', aggfunc = 'count').reset_index()

#–ø–æ—Å—á–∏—Ç–∞–µ–º –¥–æ–ª—é –∫–∞–∂–¥–æ–π –≥—Ä—É–ø–ø—ã –æ—Ç –æ–±—â–µ–≥–æ –∫–æ–ª–∏—á–µ—Å—Ç–≤–∞ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π
def share(col):
    return "{0:.2f}%".format(col/len(df)) 

children_debt['share']=children_debt['children'].apply(share) 
children_debt

  children_category  debt  children  share
0         –µ—Å—Ç—å –¥–µ—Ç–∏     0      6336  0.30%
1         –µ—Å—Ç—å –¥–µ—Ç–∏     1       647  0.03%
2       –º–Ω–æ–≥–æ–¥–µ—Ç–Ω—ã–µ     0       349  0.02%
3       –º–Ω–æ–≥–æ–¥–µ—Ç–Ω—ã–µ     1        31  0.00%
4         –Ω–µ—Ç –¥–µ—Ç–µ–π     0     13028  0.61%
5         –Ω–µ—Ç –¥–µ—Ç–µ–π     1      1063  0.05%

<div style="border:solid PaleVioletRed 2px; padding: 20px"> 
–≠—Ç–æ –ø–æ–ø—ã—Ç–∫–∞ –ø—Ä–æ–¥–µ–ª–∞—Ç—å –≥—Ä—É–ø–ø–∏—Ä–æ–≤–∫—É –º–µ—Ç–æ–¥–æ–º pivot_table, –∞ –Ω–µ groupby. –° –º–µ—Ç–æ–¥–æ–º –≤—Å–µ –±–æ–ª–µ–µ –º–µ–Ω–µ–µ –ø–æ–Ω—è—Ç–Ω–æ. –í –¥–∞–Ω–Ω–æ–π —Å–ª—É—á–∞–µ –≤–æ–∑–Ω–∏–∫ –≤–æ–ø—Ä–æ—Å, –∫–∞–∫–æ–π —Å—Ç–æ–ª–±–µ—Ü –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å –¥–ª—è –ø–∞—Ä–∞–º–µ—Ç—Ä–∞ values. –î–ª—è —Ñ—É–Ω–∫—Ü–∏–∏ count, –∫–∞–∂–µ—Ç—Å—è, –ø–æ–¥—Ö–æ–¥–∏–ª –ª—é–±–æ–π.
    
–ö–∞–∫ –≤ —Ç–∞–∫–æ–º —Å–ª—É—á–∞–µ –Ω–µ–≥—Ä–æ–º–æ–∑–¥–∫–æ –ø–æ—Å—á–∏—Ç–∞—Ç—å –¥–æ–ª—é –æ—Ç –≥—Ä—É–ø–ø—ã, –∞ –Ω–µ –æ—Ç –≤—Å–µ–π –≤—ã–±–æ—Ä–∫–∏ (—Å–ª–µ–¥—É—é—â–∏–π –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π), —è –Ω–µ –∑–Ω–∞—é.
–ü—Ä–∏–¥—É–º–∞–ª–æ—Å—å —Ç–æ–ª—å–∫–æ —Å–ª–µ–¥—É—é—â–µ–µ –æ—á–µ–Ω—å –æ–±—ä–µ–º–Ω–æ–µ –∏ –ø—É—Ç–∞–Ω–Ω–æ–µ —Ä–µ—à–µ–Ω–∏–µ, –Ω–æ —Ä–µ–∑—É–ª—å—Ç–∞—Ç –¥–æ—Å—Ç–∏–≥–∞–µ—Ç—Å—è. 
</div>

<div class="alert alert-success">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ v2 </h2>

–†–µ—à–µ–Ω–∏–µ –∑–¥–µ—Å—å –æ—á–µ–Ω—å –ø—Ä–æ—Å—Ç–æ–µ. –ú–æ–∂–Ω–æ –≤–∑—è—Ç—å —Å—Ä–µ–¥–Ω–µ–µ –ø–æ —Å—Ç–æ–ª–±—Ü—É `debt` –¥–ª—è –∫–∞–∂–¥–æ–π –≥—Ä—É–ø–ø—ã. –¢.–µ —Ç–∞–∫

</div>

In [41]:
df.pivot_table(index = 'children_category', 
               values = 'debt', 
               aggfunc = 'mean').reset_index().style.format({'debt': '{:.2%}'})

In [23]:
#–≤—ã–¥–µ–ª–∏–º —Å—Ä–µ–∑—ã –∏–∑ –Ω–∞–±–æ—Ä–∞ –¥–∞–Ω–Ω—ã—Ö –¥–ª—è —Ä–∞–∑–Ω—ã—Ö –∫–∞—Ç–µ–≥–æ—Ä–∏–π –ø–æ –Ω–∞–ª–∏—á–∏—é –¥–µ—Ç–µ–π

children_debt_1 = children_debt[children_debt['children_category']=='–µ—Å—Ç—å –¥–µ—Ç–∏']
children_debt_2 = children_debt[children_debt['children_category']=='–Ω–µ—Ç –¥–µ—Ç–µ–π']
children_debt_3 = children_debt[children_debt['children_category']=='–º–Ω–æ–≥–æ–¥–µ—Ç–Ω—ã–µ']

#–ø–æ—Å—á–∏—Ç–∞–µ–º —á–∏—Å–ª–µ–Ω–Ω–æ—Å—Ç—å –≥—Ä—É–ø–ø

children_debt_1_sum = children_debt[children_debt['children_category']=='–µ—Å—Ç—å –¥–µ—Ç–∏']['children'].sum()
children_debt_2_sum = children_debt[children_debt['children_category']=='–Ω–µ—Ç –¥–µ—Ç–µ–π']['children'].sum()
children_debt_3_sum = children_debt[children_debt['children_category']=='–º–Ω–æ–≥–æ–¥–µ—Ç–Ω—ã–µ']['children'].sum()

#–ø–æ—Å—á–∏—Ç–∞–µ–º –æ—Ç–Ω–æ—Å–∏—Ç–µ–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –≤–Ω—É—Ç—Ä–∏ –≥—Ä—É–ø–ø—ã.
#—è –Ω–µ –º–æ–≥—É –Ω–∞–ø–∏—Å–∞—Ç—å –æ–¥–Ω—É —Ñ—É–Ω–∫—Ü–∏—é –¥–ª—è —Ç—Ä–µ—Ö —Å–ª—É—á–∞–µ–≤, –ø–æ—Ç–æ–º—É —á—Ç–æ –Ω–µ –ø–æ–Ω–∏–º–∞—é, 
#–∫–∞–∫ –ø–µ—Ä–µ–¥–∞—Ç—å –∞—Ä–≥—É–º–µ–Ω—Ç children_debt_1_sum –ø—Ä–∏ –º–µ—Ç–æ–¥–µ apply

#–ø–æ–ª—É—á–∞–µ—Ç—Å—è —É–∂–∞—Å–Ω–æ, –Ω–æ –ø–æ–ª—É—á–∞–µ—Ç—Å—è :)

def share_in_group(col): 
    return "{0:.3f}%".format(col/children_debt_1_sum)
children_debt_1['share_in_group']=children_debt_1['children'].apply(share_in_group)


def share_in_group(col):
    return "{0:.3f}%".format(col/children_debt_2_sum)
children_debt_2['share_in_group']=children_debt_2['children'].apply(share_in_group)


def share_in_group(col):
    return "{0:.3f}%".format(col/children_debt_3_sum)
children_debt_3['share_in_group']=children_debt_3['children'].apply(share_in_group)


total = [children_debt_1, children_debt_2, children_debt_3 ]
total = pd.concat(total)
total

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  children_category  debt  children  share share_in_group
0         –µ—Å—Ç—å –¥–µ—Ç–∏     0      6336  0.30%         0.907%
1         –µ—Å—Ç—å –¥–µ—Ç–∏     1       647  0.03%         0.093%
4         –Ω–µ—Ç –¥–µ—Ç–µ–π     0     13028  0.61%         0.925%
5         –Ω–µ—Ç –¥–µ—Ç–µ–π     1      1063  0.05%         0.075%
2       –º–Ω–æ–≥–æ–¥–µ—Ç–Ω—ã–µ     0       349  0.02%         0.918%
3       –º–Ω–æ–≥–æ–¥–µ—Ç–Ω—ã–µ     1        31  0.00%         0.082%

<div class="alert alert-warning">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ v2 </h2>

–ü—Ä–∏ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏–∏ —è—á–µ–π–∫–∏ –≤—ã—à–µ –≤—ã—Ö–æ–¥–∏—Ç –æ—à–∏–±–∫–∞ `SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame`, –ø–æ–¥—Å–≤–µ—á–µ–Ω–Ω–∞—è —Ä–æ–∑–æ–≤—ã–º —Ü–≤–µ—Ç–æ–º (–∞ –∑–Ω–∞—á–∏—Ç, –æ–Ω–∞ –≤–∞–∂–Ω–∞ –¥–ª—è –∫–∞—á–µ—Å—Ç–≤–∞ –∫–æ–¥–∞). –î–µ–ª–æ –≤ —Ç–æ–º, —á—Ç–æ –ø—Ä–∏ –ø—Ä–∏–º–µ–Ω–µ–Ω–∏–∏ `apply` –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è —Ü–µ–ø–Ω–æ–µ –∏–Ω–¥–µ–∫—Å–∏—Ä–æ–≤–∞–Ω–∏–µ (—Ç.–µ —Ñ—É–Ω–∫—Ü–∏—è –≤—ã–ø–æ–ª–Ω—è–µ—Ç—Å—è –¥–ª—è –∫–∞–∂–¥–æ–≥–æ –∏–Ω–¥–µ–∫—Å–∞), –∞ –≤ —Ç–≤–æ–µ–º —Å–ª—É—á–∞–µ, –¥–∞—Ç–∞—Ñ—Ä–µ–π–º—ã –∏–º–µ—é—Ç –Ω–µ–ø–æ—Å–ª–µ–¥–æ–≤–∞—Ç–µ–ª—å–Ω—É—é –∏–Ω–¥–µ–∫—Å–∞—Ü–∏—é. –†–µ—à–∏—Ç—å –ø—Ä–æ–±–ª–µ–º—É –ø–æ–∑–≤–æ–ª–∏—Ç:
- —Å–±—Ä–∞—Å—ã–≤–∞–Ω–∏–µ –∏–Ω–¥–µ–∫—Å–æ–≤ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞, –º–æ–∂–Ω–æ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å [reset_index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reset_index.html)
- –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ [loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) –∏ [iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html)
- –º–æ–∂–Ω–æ –æ—Ç–∫–ª—é—á–∏—Ç—å –¥–∞–Ω–Ω–æ–µ –ø—Ä–µ–¥—É–ø—Ä–µ–∂–¥–µ–Ω–∏–µ –ø—Ä–æ–ø–∏—Å–∞–≤ `pd.options.mode.chained_assignment = None` –ø–µ—Ä–µ–¥ –∏—Å–ø–æ–ª–Ω–µ–Ω–µ–º —è—á–µ–π–∫–∏ üòâ

</div>

<div class="alert alert-danger">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ </h2>

–¢–≤–æ—è —Ä–µ–∞–ª–∏–∑–∞—Ü–∏—è –≤—ã–≤–æ–¥–∞ —Ä–µ–∑—É–ª—å—Ç–∞—Ç–æ–≤ –≤–ø–æ–ª–Ω–µ —Ä–∞–±–æ—á–∞—è, –æ–¥–Ω–∞–∫–æ –æ—á–µ–Ω—å –≥—Ä–æ–º–æ–∑–¥–∫–∞—è. –í –¥–∞–Ω–Ω–æ–º —Å–ª—É—á–∞–µ –±–æ–ª–µ–µ –∫–æ—Ä–æ—Ç–∫–∏–º —Ä–µ—à–µ–Ω–∏–µ–º –±—É–¥–µ—Ç –ø–æ—Å—Ç—Ä–æ–µ–Ω–∏–µ [—Å–≤–æ–¥–Ω—ã—Ö —Ç–∞–±–ª–∏—Ü](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html). –≠—Ç–æ –æ—á–µ–Ω—å –≤–∞–∂–Ω—ã–π –∏ –ø–æ–ø—É–ª—è—Ä–Ω—ã–π, –Ω—É–∂–Ω—ã–π –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç, –º–Ω–µ –Ω—É–∂–Ω–æ —É–±–µ–¥–∏—Ç—å—Å—è, —á—Ç–æ —Ç—ã —É–º–µ–µ—à—å –∏–º –ø–æ–ª—å–∑–æ–≤–∞—Ç—å—Å—è. –†–µ–∞–ª–∏–∑—É–π —Ç–æ –∂–µ —Å–∞–º–æ–µ –∏—Å–ø–æ–ª—å–∑—É—è `pivot_table()` –∏ –¥–∞–π –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏, –Ω–∞—Å–∫–æ–ª—å–∫–æ —É–¥–æ–±–µ–Ω –¥–ª—è —Ç–µ–±—è –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç.
    
</div>

### –í—ã–≤–æ–¥

–ï—Å–ª–∏ –≤—ã–¥–µ–ª—è—Ç—å –¥–æ–ª–∏ –≤–Ω—É—Ç—Ä–∏ –≥—Ä—É–ø–ø—ã, —Ç–æ –ø–æ–ª—É—á–∞–µ—Ç—Å—è, —á—Ç–æ –¥–æ–ª—è –∑–∞–¥–æ–ª–∂–Ω–∏–∫–æ–≤ —Å –¥–µ—Ç—å–º–∏ –≤—ã—à–µ, —á–µ–º –±–µ–∑.


–°—Ç–∞—Ä—ã–π –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π. –î–æ–ª—è –∑–∞–¥–æ–ª–∂–Ω–∏–∫–æ–≤ –±–µ–∑ –¥–µ—Ç–µ–π –≤—ã—à–µ, —á–µ–º —Å –¥–µ—Ç—å–º–∏. –ò–Ω—Ç–µ—Ä–µ—Å–Ω–æ –ø–æ—Å–º–æ—Ç—Ä–µ—Ç—å, –∫–∞–∫ —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–µ–Ω—ã –¥–æ—Ö–æ–¥—ã –º–µ–∂–¥—É –∑–∞–µ–º—â–∏–∫–∞–º–∏ —Å –¥–µ—Ç—å–º–∏ –∏ –±–µ–∑.

In [24]:
children_income = df.pivot_table(index = ['children_category', 'total_income_group'], values = 'children', aggfunc = ['count'])
children_income

                                        count
                                     children
children_category total_income_group
–µ—Å—Ç—å –¥–µ—Ç–∏         –≤—ã—Å–æ–∫–∏–π                2971
                  –≤—ã—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ          3297
                  –Ω–∏–∑–∫–∏–π –¥–æ—Ö–æ–¥             58
                  –æ—á–µ–Ω—å –≤—ã—Å–æ–∫–∏–π            85
                  —Å—Ä–µ–¥–Ω–∏–π –¥–æ—Ö–æ–¥           572
–º–Ω–æ–≥–æ–¥–µ—Ç–Ω—ã–µ       –≤—ã—Å–æ–∫–∏–π                 172
                  –≤—ã—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ           172
                  –Ω–∏–∑–∫–∏–π –¥–æ—Ö–æ–¥              1
                  –æ—á–µ–Ω—å –≤—ã—Å–æ–∫–∏–π             6
                  —Å—Ä–µ–¥–Ω–∏–π –¥–æ—Ö–æ–¥            29
–Ω–µ—Ç –¥–µ—Ç–µ–π         –≤—ã—Å–æ–∫–∏–π                5819
                  –≤—ã—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ          6525
                  –Ω–∏–∑–∫–∏–π –¥–æ—Ö–æ–¥            158
                  –æ—á–µ–Ω—å –≤—ã—Å–æ–∫–∏–π           131
                  —Å—Ä–µ–¥–Ω–∏–π –¥–æ—Ö–æ–¥          1458

–£ –∫–ª–∏–µ–Ω—Ç–æ–≤ —Å –¥–µ—Ç—å–º–∏ –≤ —Å—Ä–µ–¥–Ω–µ–º –≤—ã—Å–æ–∫–∏–π –¥–æ—Ö–æ–¥ –≤—Å—Ç—Ä–µ—á–∞–µ—Ç—Å—è —á–∞—â–µ.

- –ï—Å—Ç—å –ª–∏ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç—å –º–µ–∂–¥—É —Å–µ–º–µ–π–Ω—ã–º –ø–æ–ª–æ–∂–µ–Ω–∏–µ–º –∏ –≤–æ–∑–≤—Ä–∞—Ç–æ–º –∫—Ä–µ–¥–∏—Ç–∞ –≤ —Å—Ä–æ–∫?

In [25]:
marriage_debt = df.pivot_table(index = ['marriage_status', 'debt'], values = 'family_status', aggfunc = 'count').reset_index()

def share(col):
    return "{0:.2f}%".format(col/len(df)) 

marriage_debt['share']=marriage_debt['family_status'].apply(share)


marriage_debt_true = marriage_debt[marriage_debt['marriage_status']=='–≤ –±—Ä–∞–∫–µ']
marriage_debt_true_sum = marriage_debt[marriage_debt['marriage_status']=='–≤ –±—Ä–∞–∫–µ']['family_status'].sum()

def share_in_group(col):
    return "{0:.2f}%".format(col/marriage_debt_true_sum)

marriage_debt_true['share_in_group']=marriage_debt_true['family_status'].apply(share_in_group)

marriage_debt_false = marriage_debt[marriage_debt['marriage_status']=='–Ω–µ –≤ –±—Ä–∞–∫–µ']
marriage_debt_false_sum = marriage_debt[marriage_debt['marriage_status']=='–Ω–µ –≤ –±—Ä–∞–∫–µ']['family_status'].sum()

def share_in_group(col):
    return "{0:.2f}%".format(col/marriage_debt_false_sum)

marriage_debt_false['share_in_group']=marriage_debt_false['family_status'].apply(share_in_group)
total = [marriage_debt_false, marriage_debt_true]
total = pd.concat(total)
total

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  marriage_status  debt  family_status  share share_in_group
2      –Ω–µ –≤ –±—Ä–∞–∫–µ     0           4542  0.21%          0.91%
3      –Ω–µ –≤ –±—Ä–∞–∫–µ     1            422  0.02%          0.09%
0         –≤ –±—Ä–∞–∫–µ     0          15171  0.71%          0.92%
1         –≤ –±—Ä–∞–∫–µ     1           1319  0.06%          0.08%

<div class="alert alert-danger">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ </h2>

–¢–∞–∫–∂–µ –∑–¥–µ—Å—å —Ç—ã —Å–º–æ—Ç—Ä–∏—à—å –æ—Ç–Ω–æ—Å–∏—Ç–µ–ª—å–Ω–æ –æ–±—â–µ–≥–æ –∫–æ–ª-–≤–∞ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π –∫—Ä–µ–¥–∏—Ç–∞. –ë–æ–ª–µ–µ –∏–Ω—Ñ–æ—Ä–º–∞—Ç–∏–≤–Ω—ã–º –±—É–¥–µ—Ç –ø–æ—Å—á–∏—Ç–∞—Ç—å –æ—Ç–Ω–æ—Å–∏—Ç–µ–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –≤–Ω—É—Ç—Ä–∏ –≥—Ä—É–ø–ø—ã. –¢.–µ –Ω–∞–π—Ç–∏ —Å–∫–æ–ª—å–∫–æ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π –∏–∑ –≥—Ä—É–ø–ø—ã `–≤ –±—Ä–∞–∫–µ` –∏–º–µ—é—Ç –∑–∞–¥–æ–ª–∂–µ–Ω–Ω–æ—Å—Ç—å (1319 / 16507)
    
</div>

<div style="border:solid PaleVioletRed 2px; padding: 20px"> 
 –ú–Ω–µ –∫–∞–∂–µ—Ç—Å—è, —á—Ç–æ –¥–æ–ª—è –∑–∞–¥–æ–ª–∂–Ω–∏–∫–æ–≤ –æ—Ç –æ–±—â–µ–≥–æ –∫–æ–ª–∏—á–µ—Å—Ç–≤–∞ –∑–∞–µ–º—â–∏–∫–æ–≤ –ø–æ–∫–∞–∑–∞—Ç–µ–ª—å–Ω–µ–µ, –ø–æ—Ç–æ–º—É —á—Ç–æ –≤ –ª—é–±–æ–π –≥—Ä—É–ø–ø–µ –¥–æ–ª—è –ª—é–¥–µ–π –±–µ–∑ –¥–æ–ª–≥–∞ –≤—Å–µ–≥–¥–∞ –≤—ã—à–µ.
–í—ã—à–µ —è –∫–æ—Ä—è–≤—ã–º —Å–ø–æ—Å–æ–±–æ–º –ø–æ—Å—á–∏—Ç–∞–ª–∞ –¥–æ–ª–∏ –æ—Ç –∫–∞—Ç–µ–≥–æ—Ä–∏–∏, –ø–æ –Ω–∏–º —è –Ω–µ –º–æ–≥—É —Å–¥–µ–ª–∞—Ç—å –≤—ã–≤–æ–¥. –í–æ–∑–º–æ–∂–Ω–æ, –ª—É—á—à–µ —Å—Ä–∞–≤–Ω–∏–≤–∞—Ç—å –¥–æ–ª—é –¥–æ–ª–∂–Ω–∏–∫–æ–≤ –∫–æ–Ω–∫—Ä–µ—Ç–Ω–æ–π –∫–∞—Ç–µ–≥–æ—Ä–∏–∏ –æ—Ç –æ–±—â–µ–≥–æ –∫–æ–ª–∏—á–µ—Å—Ç–≤–∞ –¥–æ–ª–∂–Ω–∏–∫–æ–≤. –ù–æ –∫–∞–∂–µ—Ç—Å—è, —á—Ç–æ —Ç—É—Ç —è –∫–æ–Ω–∫—Ä–µ—Ç–Ω–æ –∑–∞–ø—É—Ç–∞–ª–∞—Å—å. 
</div>

In [26]:
marriage_debt = df.pivot_table(index = ['marriage_status', 'debt'], values = 'family_status', aggfunc = 'count').reset_index()

def share(col):
    return "{0:.2f}%".format(col/len(df)) 

marriage_debt['share']=marriage_debt['family_status'].apply(share)


marriage_debt_true = marriage_debt[marriage_debt['debt']==1]
marriage_debt_true_sum = marriage_debt[marriage_debt['debt']==1]['family_status'].sum()

def share_in_group(col):
    return "{0:.2f}%".format(col/marriage_debt_true_sum)

marriage_debt_true['share_in_group']=marriage_debt_true['family_status'].apply(share_in_group)

marriage_debt_false = marriage_debt[marriage_debt['debt']==0]
marriage_debt_false_sum = marriage_debt[marriage_debt['debt']==0]['family_status'].sum()

def share_in_group(col):
    return "{0:.2f}%".format(col/marriage_debt_false_sum)

marriage_debt_false['share_in_group']=marriage_debt_false['family_status'].apply(share_in_group)
total = [marriage_debt_false, marriage_debt_true]
total = pd.concat(total)
total

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  marriage_status  debt  family_status  share share_in_group
0         –≤ –±—Ä–∞–∫–µ     0          15171  0.71%          0.77%
2      –Ω–µ –≤ –±—Ä–∞–∫–µ     0           4542  0.21%          0.23%
1         –≤ –±—Ä–∞–∫–µ     1           1319  0.06%          0.76%
3      –Ω–µ –≤ –±—Ä–∞–∫–µ     1            422  0.02%          0.24%

<div style="border:solid PaleVioletRed 2px; padding: 20px">  –í —Å—Ç–æ–ª–±—Ü–µ share_in_group –≤–∏–¥–Ω–æ, —á—Ç–æ –¥–æ–ª—è –ª—é–¥–µ–π –≤ –±—Ä–∞–∫–µ —Å—Ä–µ–¥–∏ –Ω–µ–≤–æ–∑–≤—Ä–∞—â–∞—é—â–∏—Ö –≤—ã—à–µ.  
</div>

–ü—Ä–æ–±–ª–µ–º —Å –≤–æ–∑–≤—Ä–∞—Ç–æ–º –±–æ–ª—å—à–µ —É —Å–æ—Å—Ç–æ—è—â–∏—Ö –≤ –±—Ä–∞–∫–µ, —á–µ–º —É –æ–¥–∏–Ω–æ–∫–∏—Ö –ª—é–¥–µ–π. –î–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ –ø–æ—Å–º–æ—Ç—Ä–∏–º, –∫–∞–∫ –º–Ω–æ–≥–æ –∑–∞–¥–æ–ª–∂–Ω–æ—Å—Ç–µ–π —É –∂–µ–Ω–∞—Ç—ã—Ö/–∑–∞–º—É–∂–Ω—ã—Ö —Å –¥–µ—Ç—å–º–∏ –∏ –±–µ–∑.

In [27]:
marriage_children = df.pivot_table(index = ['marriage_status', 'children_category', 'debt'], values = ['children'], aggfunc = ['count'])
display(marriage_children)

                                          count
                                       children
marriage_status children_category debt
–≤ –±—Ä–∞–∫–µ         –µ—Å—Ç—å –¥–µ—Ç–∏         0        5395
                                  1         546
                –º–Ω–æ–≥–æ–¥–µ—Ç–Ω—ã–µ       0         323
                                  1          28
                –Ω–µ—Ç –¥–µ—Ç–µ–π         0        9453
                                  1         745
–Ω–µ –≤ –±—Ä–∞–∫–µ      –µ—Å—Ç—å –¥–µ—Ç–∏         0         941
                                  1         101
                –º–Ω–æ–≥–æ–¥–µ—Ç–Ω—ã–µ       0          26
                                  1           3
                –Ω–µ—Ç –¥–µ—Ç–µ–π         0        3575
                                  1         318

### –í—ã–≤–æ–¥

–ß–∏—Å–ª–æ –∑–∞–¥–æ–ª–∂–Ω–∏–∫–æ–≤ –±–µ–∑ –¥–µ—Ç–µ–π –≤—ã—à–µ –∏ —Å—Ä–µ–¥–∏ –∂–µ–Ω–∞—Ç—ã—Ö, –∏ —Å—Ä–µ–¥–∏ –æ–¥–∏–Ω–æ–∫–∏—Ö.

- –ï—Å—Ç—å –ª–∏ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç—å –º–µ–∂–¥—É —É—Ä–æ–≤–Ω–µ–º –¥–æ—Ö–æ–¥–∞ –∏ –≤–æ–∑–≤—Ä–∞—Ç–æ–º –∫—Ä–µ–¥–∏—Ç–∞ –≤ —Å—Ä–æ–∫?

In [28]:
income_debt = df.pivot_table(index = ['total_income_group', 'debt'], values = 'total_income', aggfunc = 'count').reset_index()

def share(col):
    return "{0:.2f}%".format(col/len(df)) 

income_debt['share']=income_debt['total_income'].apply(share)

income_debt

  total_income_group  debt  total_income  share
0            –≤—ã—Å–æ–∫–∏–π     0          8250  0.38%
1            –≤—ã—Å–æ–∫–∏–π     1           712  0.03%
2      –≤—ã—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ     0          9153  0.43%
3      –≤—ã—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ     1           841  0.04%
4       –Ω–∏–∑–∫–∏–π –¥–æ—Ö–æ–¥     0           203  0.01%
5       –Ω–∏–∑–∫–∏–π –¥–æ—Ö–æ–¥     1            14  0.00%
6      –æ—á–µ–Ω—å –≤—ã—Å–æ–∫–∏–π     0           208  0.01%
7      –æ—á–µ–Ω—å –≤—ã—Å–æ–∫–∏–π     1            14  0.00%
8      —Å—Ä–µ–¥–Ω–∏–π –¥–æ—Ö–æ–¥     0          1899  0.09%
9      —Å—Ä–µ–¥–Ω–∏–π –¥–æ—Ö–æ–¥     1           160  0.01%

### –í—ã–≤–æ–¥

–õ—é–¥–∏ —Å –≤—ã—Å–æ–∫–∏–º –¥–æ—Ö–æ–¥–æ–º –∏ —Å –¥–æ—Ö–æ–¥–æ–º –≤—ã—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ —á–∞—â–µ –∏–º–µ—é—Ç –∑–∞–¥–æ–ª–∂–µ–Ω–Ω–æ—Å—Ç—å –ø–æ –∫—Ä–µ–¥–∏—Ç—É, —á–µ–º —Å –Ω–∏–∑–∫–∏–º, —Å—Ä–µ–¥–Ω–∏–º –∏ –æ—á–µ–Ω—å –≤—ã—Å–æ–∫–∏–º. –ú–æ–∂–Ω–æ –ø—Ä–µ–¥–ø–æ–ª–æ–∂–∏—Ç—å, —á—Ç–æ —Ç–µ, –∫—Ç–æ –ø–æ–ª—É—á–∞—é—Ç –º–∞–ª–æ, –Ω–µ –≥–æ—Ç–æ–≤—ã –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ –ø–ª–∞—Ç–∏—Ç—å –∏ –∑–∞ –ø—Ä–æ—Å—Ä–æ—á–µ–Ω–Ω—ã–π –ø–ª–∞—Ç–µ–∂ –ø–æ –∫—Ä–µ–¥–∏—Ç—É, –∞ —É –ª—é–¥–µ–π —Å –≤—ã—Å–æ–∫–∏–º –¥–æ—Ö–æ–¥–æ–º –ø—Ä–æ–±–ª–µ–º —Å –≤—ã–ø–ª–∞—Ç–∞–º–∏ –Ω–µ –≤–æ–∑–Ω–∏–∫–∞–µ—Ç.

- –ö–∞–∫ —Ä–∞–∑–Ω—ã–µ —Ü–µ–ª–∏ –∫—Ä–µ–¥–∏—Ç–∞ –≤–ª–∏—è—é—Ç –Ω–∞ –µ–≥–æ –≤–æ–∑–≤—Ä–∞—Ç –≤ —Å—Ä–æ–∫?

<div class="alert alert-danger">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ </h2>

–ü—Ä–∏ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏–∏ —Ä–∞–±–æ—Ç—ã –≤–∞–∂–Ω–æ —Å–æ–±–ª—é–¥–∞—Ç—å —Å—Ç—Ä—É–∫—Ç—É—Ä—É, –∫–æ—Ç–æ—Ä–∞—è –¥–∞–Ω–∞ –≤ –æ–ø–∏—Å–∞–Ω–∏–∏ –ø—Ä–æ–µ–∫—Ç–∞, –æ–Ω–∞ –ø–æ–º–æ–∂–µ—Ç —Ç–µ–±–µ –ø–æ—Å—Ç—Ä–æ–∏—Ç—å –ø–æ—Å–ª–µ–¥–æ–≤–∞—Ç–µ–ª—å–Ω–æ–µ –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏–µ. –ü–æ—ç—Ç–æ–º—É –ø–µ—Ä–µ–Ω–µ—Å–∏, –ø–æ–∂–∞–ª—É–π—Å—Ç–∞, –ª–µ–º–º–∞—Ç–∏–∑–∞—Ü–∏—é –≤ —Ä–∞–∑–¥–µ–ª –ª–µ–º–º–∞—Ç–∏–∑–∞—Ü–∏–∏ –∏–ª–∏ –∫–∞—Ç–µ–≥–æ—Ä–∏–∑–∞—Ü–∏–∏ üôÉ.

</div>

In [29]:
purpose_debt = df.pivot_table(index = ['category_purpose', 'debt'], values = 'purpose', aggfunc = 'count').reset_index()

def share(col):
    return "{0:.2f}%".format(col/len(df)) 

purpose_debt['share']=purpose_debt['purpose'].apply(share)    
purpose_debt

   category_purpose  debt  purpose  share
0        –∞–≤—Ç–æ–º–æ–±–∏–ª—å     0     3903  0.18%
1        –∞–≤—Ç–æ–º–æ–±–∏–ª—å     1      403  0.02%
2             –∂–∏–ª—å–µ     0     3548  0.17%
3             –∂–∏–ª—å–µ     1      260  0.01%
4      –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç—å     0     4082  0.19%
5      –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç—å     1      317  0.01%
6       –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ     0     3643  0.17%
7       –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ     1      370  0.02%
8          –æ–ø–µ—Ä–∞—Ü–∏—è     0     2399  0.11%
9          –æ–ø–µ—Ä–∞—Ü–∏—è     1      205  0.01%
10          —Å–≤–∞–¥—å–±–∞     0     2138  0.10%
11          —Å–≤–∞–¥—å–±–∞     1      186  0.01%

### –í—ã–≤–æ–¥

–°–∞–º–∞—è –≤—ã—Å–æ–∫–∞—è –¥–æ–ª—è –∑–∞–¥–æ–ª–∂–Ω–∏–∫–æ–≤ - —Ç–µ, –∫—Ç–æ –±—Ä–∞–ª–∏ –∫—Ä–µ–¥–∏—Ç –¥–ª—è –ø–æ–∫—É–ø–∫–∏ –∞–≤—Ç–æ–º–æ–±–∏–ª—è.

### –®–∞–≥ 4. –û–±—â–∏–π –≤—ã–≤–æ–¥

–ü–µ—Ä–µ–¥ –Ω–∞—á–∞–ª–æ–º –∞–Ω–∞–ª–∏–∑–∞ –±—ã–ª–∞ –ø—Ä–æ–≤–µ–¥–µ–Ω–∞ –ø—Ä–µ–¥–æ–±—Ä–∞–±–æ—Ç–∫–∞ –¥–∞–Ω–Ω—ã—Ö: 
- –ø—Ä–æ–ø—É—â–µ–Ω–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –≤ —Å—Ç–æ–ª–±—Ü–µ days_employed –±—ã–ª–∏ –∑–∞–º–µ–Ω–µ–Ω—ã –Ω–∞ —Å—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –∏ –≤ —Å—Ç–æ–ª–±—Ü–µ total_income –Ω–∞ –º–µ–¥–∏–∞–Ω–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ. - —É–¥–∞–ª–µ–Ω—ã –¥—É–±–ª–∏–∫–∞—Ç—ã –≤ —Å—Ç–æ–ª–±—Ü–µ education
- —É–¥–∞–ª–µ–Ω—ã –ø–æ–≤—Ç–æ—Ä—è—é—â–∏–µ—Å—è —Å—Ç—Ä–æ–∫–∏
- —É—Å—Ç—Ä–∞–Ω–µ–Ω–Ω—ã –æ—à–∏–±–æ—á–Ω—ã–µ –æ—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –∏ –æ–ø–µ—á–∞—Ç–∫–∞ –≤ —Å—Ç–æ–ª–±—Ü–µ children.

–¢–∞–∫–∂–µ –±—ã–ª–∏ –≤—ã–¥–µ–ª–µ–Ω–Ω—ã–µ –∫–ª—é—á–µ–≤—ã–µ —Å–ª–æ–≤–∞ –¥–ª—è —Å—Ç–æ–ª–±—Ü–∞ purpose –∏ –æ–ø—Ä–µ–¥–ª–µ–Ω—ã —Å–∞–º—ã–µ –ø–æ–ø—É–ª—è—Ä–Ω—ã–µ —Ü–µ–ª–∏ –¥–ª—è –∫—Ä–µ–¥–∏—Ç–æ–≤ - –ø—Ä–∏–æ–±—Ä–µ—Ç–µ–Ω–∏–µ –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç–∏ –∏ –∂–∏–ª—å—è,–ø–æ–∫—É–ø–∫–∞ –∞–≤—Ç–æ–º–æ–±–∏–ª—è, –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ, –æ–ø–µ—Ä–∞—Ü–∏–∏ –∏ —Å–≤–∞–¥—å–±—ã.

–î–∞–Ω–Ω—ã–µ –±—ã–ª–∏ —Ä–∞–∑–¥–µ–ª–µ–Ω—ã –Ω–∞ –Ω–µ—Å–∫–æ–ª—å–∫–æ –∫–∞—Ç–µ–≥–æ—Ä–∏–π - –ø–æ –Ω–∞–ª–∏—á–∏—é –¥–µ—Ç–µ–π, —Å–µ–º–µ–π–Ω–æ–º—É –ø–æ–ª–æ–∂–µ–Ω–∏—é, –¥–æ—Ö–æ–¥—É –∏ —Ü–µ–ª—è–º. –í –¥–∞—Ç–∞—Ñ—Ä–µ–π–º –¥–æ–±–∞–≤–ª–µ–Ω—ã —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤—É—é—â–∏–µ —Å—Ç–æ–ª–±—Ü—ã -children_category, marriage_status, total_income_group, category_purpose

–ù–∞–ª–∏—á–∏–µ –¥–µ—Ç–µ–π –Ω–µ –≤–ª–∏—è–µ—Ç –Ω–∞ —Ñ–∞–∫—Ç –ø–æ–≥–∞—à–µ–Ω–∏—è –∫—Ä–µ–¥–∏—Ç–∞ –≤ —Å—Ä–æ–∫, –∞ –≤–æ—Ç –∏—Ö –æ—Ç—Å—Ç—É—Ç–≤–∏–µ, –Ω–∞–æ–±–æ—Ä–æ—Ç, –ø–æ–≤—ã—à–∞–µ—Ç –≤–µ—Ä–æ—è—Ç–Ω–æ—Å—Ç—å —Å—Ç–∞—Ç—å –∑–∞–¥–æ–ª–∂–Ω–∏–∫–æ–º.
–ó–∞–¥–æ–ª–∂–µ–Ω–Ω–æ—Å—Ç—å –ø–æ –∫—Ä–µ–¥–∏—Ç—É —á–∞—â–µ –≤–æ–∑–Ω–∏–∫–∞–µ—Ç —É –ª—é–¥–µ–π –∂–µ–Ω–∞—Ç—ã—Ö/–∑–∞–º—É–∂–Ω–∏—Ö. 
–£ –ª—é–¥–µ–π —Å –≤—ã—Å–æ–∫–∏–º –¥–æ—Ö–æ–¥–æ–º –∏ –¥–æ—Ö–æ–¥–æ–º –≤—ã—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ –∑–∞–¥–æ–ª–∂–µ–Ω–Ω–æ—Å—Ç–∏ –≤–æ–∑–Ω–∏–∫–∞—é—Ç —á–∞—â–µ, —á–µ–º —É –ª—é–¥–µ–π —Å –Ω–∏–∑–∫–∏–º, —Å—Ä–µ–¥–Ω–∏–º –∏ –æ—á–µ–Ω—å –≤—ã—Å–æ–∫–∏–º.
–¶–µ–ª—å –∫—Ä–µ–¥–∏—Ç–∞ - –∞–≤—Ç–æ–º–æ–±–∏–ª—å - —Å–∞–º–∞—è –ø–æ–ø—É–ª—è—Ä–Ω–∞—è —Å—Ä–µ–¥–∏ –¥–æ–ª–∂–Ω–∏–∫–æ–≤.

<div class="alert alert-danger">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ </h2>

–í –æ–±—â–∏–π –≤—ã–≤–æ–¥ —Å—Ç–æ–∏—Ç –¥–æ–±–∞–≤–∏—Ç—å —Ä–µ–∑—É–ª—å—Ç–∞—Ç—ã —Ä–∞–±–æ—Ç –Ω–∞ –≤—Ç–æ—Ä–æ–º –∏ —Ç—Ä–µ—Ç—å–µ–º —à–∞–≥–∞—Ö, –∫–∞–∫ –±—ã–ª–∏ –æ–±—Ä–∞–±–∞—Ç–∞–Ω—ã –ø—Ä–æ–ø—É—Å–∫–∏, –∏—Ö –≤–æ–∑–º–æ–∂–Ω—ã–µ –ø—Ä–∏—á–∏–Ω—ã –∏ —Ç–¥. –≠—Ç–æ –ø–æ–∑–≤–æ–ª–∏—Ç –ª—é–¥—è–º, —É –∫–æ—Ç–æ—Ä—ã—Ö –Ω–µ—Ç –≤—Ä–µ–º–µ–Ω–∏ –≤–Ω–∏–∫–∞—Ç—å –≤ —Ä–∞–±–æ—Ç—É, –ø–æ–Ω—è—Ç—å —á—Ç–æ –±—ã–ª–æ —Å–¥–µ–ª–∞–Ω–æ –∏ –∫–∞–∫.
    
</div>

<div style="border:solid purple 2px; padding: 20px">

–£ —Ç–µ–±—è –ø–æ–ª—É—á–∏–ª–∞—Å—å –æ—á–µ–Ω—å —Ö–æ—Ä–æ—à–∞—è —Ä–∞–±–æ—Ç–∞! –ú–Ω–æ–≥–∏–µ –º–æ–º–µ–Ω—Ç—ã —Å–¥–µ–ª–∞–Ω—ã –ø—Ä–æ—Å—Ç–æ –ø—Ä–µ–∫—Ä–∞—Å–Ω–æ. –¢—ã –ø–æ–∫–∞–∑—ã–≤–∞–µ—à—å –æ—Ç–ª–∏—á–Ω–æ–µ –≤–ª–∞–¥–µ–Ω–∏–µ –∏–∑—É—á–∞–µ–º—ã–º –º–∞—Ç–µ—Ä–∏–∞–ª–æ–º: —É–≤–µ—Ä–µ–Ω–Ω–æ –ø–æ–ª—å–∑—É–µ—à—å—Å—è pandas, —É–º–µ–µ—à—å –ø–æ–¥–≥–æ—Ç–∞–≤–ª–∏–≤–∞—Ç—å, –æ—á–∏—â–∞—Ç—å, –æ–±–æ–≥–æ—â–∞—Ç—å –¥–∞–Ω–Ω—ã–µ. –ù–∞ –ø—Ä–æ—Ç—è–∂–µ–Ω–∏–∏ –≤—Å–µ–π —Ä–∞–±–æ—Ç—ã —á—É–≤—Å—Ç–≤—É–µ—Ç—Å—è –≥–ª—É–±–∏–Ω–∞ –ø—Ä–æ—Ä–∞–±–æ—Ç–∫–∏ –∑–∞–¥–∞—á–∏ –∏ —ç—Ç–æ –±–µ–∑—É—Å–ª–æ–≤–Ω—ã–π –ø–ª—é—Å –¥–ª—è –Ω–∞—Å.

–û—Å—Ç–∞–ª–∏—Å—å –Ω–µ–±–æ–ª—å—à–∏–µ –¥–æ—Ä–∞–±–æ—Ç–∫–∏:

- –ø–µ—Ä–µ–Ω–µ—Å—Ç–∏ –ª–µ–º–º–∞—Ç–∏–∑–∞—Ü–∏—é –≤ —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤—É—é—â–∏–π —Ä–∞–∑–¥–µ–ª;
- –í —à–∞–≥–µ 3 –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –ø–æ—Å—á–∏—Ç–∞—Ç—å –æ—Ç–Ω–æ—Å–∏—Ç–µ–ª—å–Ω—ã–µ –≥—Ä—É–ø–ø–æ–≤—ã–µ –ø–æ–∫–∞–∑–∞—Ç–µ–ª–∏;
- –í —à–∞–≥–µ 3 –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –ø–æ–ª—É—á–∏—Ç—å —Ä–µ–∑—É–ª—å—Ç–∞—Ç—ã —Å –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ–º –º–µ—Ç–æ–¥–∞ `pivot_table()`;
- –í —à–∞–≥–µ 4 –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –¥–æ–ø–æ–ª–Ω–∏—Ç—å –æ–±—â–∏–π –≤—ã–≤–æ–¥.

–ñ–¥—É —Ç–≤–æ–∏—Ö –∏—Å–ø—Ä–∞–≤–ª–µ–Ω–∏–π, —É —Ç–µ–±—è –≤—Å–µ –ø–æ–ª—É—á–∏—Ç—Å—è üòä 

</div>

<div style="border:solid PaleVioletRed 2px; padding: 20px"> 
–õ–µ–º–º–∞—Ç–∏–∑–∞—Ü–∏—é –∏ –∫–∞—Ç–µ–≥–æ—Ä–∏–∑–∞—Ü–∏—é –ø–æ —Ü–µ–ª–∏ –ø–µ—Ä–µ–Ω–µ—Å–ª–∞ –≤ —Å–æ–æ—Ç—Å—Ç–≤—É—é—â–∏–µ —Ä–∞–∑–¥–µ–ª—ã, –≥–¥–µ –∏–º –∏ –º–µ—Å—Ç–æ.
–ò—Å–ø–æ–ª—å–∑–æ–≤–∞–ª–∞ –º–µ—Ç–æ–¥ pivot_table –¥–ª—è –≤—ã–≤–æ–¥–∞ —Ä–µ–∑—É–ª—å—Ç–∞—Ç–æ–≤.
–û–±—â–∏–π –≤—ã–≤–æ–¥ –¥–æ–±–∞–≤–∏–ª–∞.
–í–æ–∑–Ω–∏–∫–ª–∏ —Ç—Ä—É–¥–Ω–æ—Å—Ç–∏ —Å –ø–æ–¥—á–µ—Ç–æ–º –æ—Ç–Ω–æ—Å–∏—Ç–µ–ª—å–Ω—ã—Ö–≥—Ä—É–ø–ø–æ–≤—ã—Ö –ø–æ–∫–∞–∑–∞—Ç–µ–ª–µ–π. –ü–æ—Å—á–∏—Ç–∞–ª–∞, –∫–∞–∫ —Å–º–æ–≥–ª–∞. –ö–∞–∫ —Å–¥–µ–ª–∞—Ç—å –∏–Ω–∞—á–µ, –Ω–∞–π—Ç–∏ –Ω–µ —É–¥–∞–ª–æ—Å—å. 
–ü–æ—Å—á–∏—Ç–∞–ª–∞ —Å–≤–æ–∏–º –∫–æ—Ä—è–≤—ã–º –º–µ—Ç–æ–¥–æ–º –¥–ª—è –¥–µ—Ç–µ–π –∏ —Å–µ–º–µ–π–Ω–æ–≥–æ –ø–æ–ª–æ–∂–µ–Ω–∏—è. –û—á–µ–Ω—å –Ω–∞–¥–µ—é—Å—å –Ω–∞ —Å–æ–≤–µ—Ç, –∫–∞–∫ —ç—Ç–æ —Å–¥–µ–ª–∞—Ç—å –º–µ–Ω—å—à–∏–º –∫–æ–ª–∏—á–µ—Å–≤—Ç–æ–º —Å—Ç—Ä–æ–∫.
–ò —É –º–µ–Ω—è –≤–æ–ø—Ä–æ—Å - –ø–æ—á–µ–º—É –ª—É—á—à–µ —Å—á–∏—Ç–∞—Ç—å –æ—Ç–Ω–æ—Å–∏—Ç–µ–ª—å–Ω—ã–µ –≥—Ä—É–ø–ø–æ–≤—ã–µ –ø–æ–∫–∞–∑–∞—Ç–µ–ª–∏, –∞ –Ω–µ, –Ω–∞–ø—Ä–∏–º–µ—Ä, –ø–æ–∫–∞–∑–∞—Ç–µ–ª–∏ –¥–æ–ª–µ–π –∫–∞—Ç–µ–≥–æ—Ä–∏–π —Å—Ä–µ–¥–∏ –¥–æ–ª–∂–Ω–∏–∫–æ–≤. 
    
–ë—É–¥—É –∂–¥–∞—Ç—å –æ—Ç–≤–µ—Ç–∞, —Å–ø–∞—Å–∏–±–æ!

</div>

<div class="alert alert-success">
<h2> –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π —Ä–µ–≤—å—é–µ—Ä–∞ v2 </h2>

–ü–æ –ø–æ–¥—Å—á–µ—Ç—É –æ—Ç–Ω–æ—Å–∏—Ç–µ–ª—å–Ω—ã—Ö –ø–æ–∫–∞–∑–∞—Ç–µ–ª–µ–π –ø–æ–∫–∞–∑–∞–ª, –∫–∞–∫ –º–æ–∂–Ω–æ –±—ã–ª–æ —Ä–µ—à–∏—Ç—å –∫–æ—Ä–æ—á–µ. –ù–∞–¥–µ—é—Å—å –≤—Å–µ –ø–æ–Ω—è—Ç–Ω–æ))) –ß—Ç–æ –∫–∞—Å–∞–µ—Ç—Å—è –ø–æ—Å–ª–µ–¥–Ω–µ–≥–æ –≤–æ–ø—Ä–æ—Å–∞, –¥–µ–ª–æ –≤ —Ç–æ–º, —á—Ç–æ –ø—Ä–∏ –ø–æ–¥—Å—á–µ—Ç–µ –æ—Ç–Ω–æ—Å–∏—Ç–µ–ª—å–Ω–æ –≤—Å–µ–≥–æ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞ –Ω–µ —Å–æ–≤—Å–µ–º –ø–æ–Ω—è—Ç–Ω–æ, –∫–∞–∫–∞—è –∫–∞—Ç–µ–≥–æ—Ä–∏—è, –Ω–∞–ø—Ä–∏–º–µ—Ä, —Ü–µ–ª–µ–π –∫—Ä–µ–¥–∏—Ç–∞ –ª—É—á—à–µ. –¢.–µ –±–∞–Ω–∫—É –Ω—É–∂–Ω–æ –ø–æ–Ω—è—Ç—å, –Ω–∞ —á—Ç–æ –≤—ã–≥–æ–¥–Ω–µ–µ –≤—ã–¥–∞–≤–∞—Ç—å –∫—Ä–µ–¥–∏—Ç, –Ω–∞ –∞–≤—Ç–æ–º–æ–±–∏–ª—å –∏–ª–∏ –Ω–∞ —Å–≤–∞–¥—å–±—É. –ê —ç—Ç–æ –º–æ–∂–Ω–æ –ø–æ–Ω—è—Ç—å —Ç–æ–ª—å–∫–æ –ø–æ—Å—á–∏—Ç–∞–≤ –æ—Ç–Ω–æ—Å–∏—Ç–µ–ª—å–Ω—ã–µ –≥—Ä—É–ø–ø–æ–≤—ã–µ –ø–æ–∫–∞–∑–∞—Ç–µ–ª–∏

</div>

### –ß–µ–∫-–ª–∏—Å—Ç –≥–æ—Ç–æ–≤–Ω–æ—Å—Ç–∏ –ø—Ä–æ–µ–∫—Ç–∞

–ü–æ—Å—Ç–∞–≤—å—Ç–µ 'x' –≤ –≤—ã–ø–æ–ª–Ω–µ–Ω–Ω—ã—Ö –ø—É–Ω–∫—Ç–∞—Ö. –î–∞–ª–µ–µ –Ω–∞–∂–º–∏—Ç–µ Shift+Enter.

- [x]  –æ—Ç–∫—Ä—ã—Ç —Ñ–∞–π–ª;
- [x]  —Ñ–∞–π–ª –∏–∑—É—á–µ–Ω;
- [x]  –æ–ø—Ä–µ–¥–µ–ª–µ–Ω—ã –ø—Ä–æ–ø—É—â–µ–Ω–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è;
- [x]  –∑–∞–ø–æ–ª–Ω–µ–Ω—ã –ø—Ä–æ–ø—É—â–µ–Ω–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è;
- [x] –µ—Å—Ç—å –ø–æ—è—Å–Ω–µ–Ω–∏–µ, –∫–∞–∫–∏–µ –ø—Ä–æ–ø—É—â–µ–Ω–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –æ–±–Ω–∞—Ä—É–∂–µ–Ω—ã;
- [x]  –æ–ø–∏—Å–∞–Ω—ã –≤–æ–∑–º–æ–∂–Ω—ã–µ –ø—Ä–∏—á–∏–Ω—ã –ø–æ—è–≤–ª–µ–Ω–∏—è –ø—Ä–æ–ø—É—Å–∫–æ–≤ –≤ –¥–∞–Ω–Ω—ã—Ö;
- [x]  –æ–±—ä—è—Å–Ω–µ–Ω–æ, –ø–æ –∫–∞–∫–æ–º—É –ø—Ä–∏–Ω—Ü–∏–ø—É –∑–∞–ø–æ–ª–Ω–µ–Ω—ã –ø—Ä–æ–ø—É—Å–∫–∏;
- [x]  –∑–∞–º–µ–Ω–µ–Ω –≤–µ—â–µ—Å—Ç–≤–µ–Ω–Ω—ã–π —Ç–∏–ø –¥–∞–Ω–Ω—ã—Ö –Ω–∞ —Ü–µ–ª–æ—á–∏—Å–ª–µ–Ω–Ω—ã–π;
- [x]  –µ—Å—Ç—å –ø–æ—è—Å–Ω–µ–Ω–∏–µ, –∫–∞–∫–æ–π –º–µ—Ç–æ–¥ –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –¥–ª—è –∏–∑–º–µ–Ω–µ–Ω–∏—è —Ç–∏–ø–∞ –¥–∞–Ω–Ω—ã—Ö –∏ –ø–æ—á–µ–º—É;
- [x]  —É–¥–∞–ª–µ–Ω—ã –¥—É–±–ª–∏–∫–∞—Ç—ã;
- [x]  –µ—Å—Ç—å –ø–æ—è—Å–Ω–µ–Ω–∏–µ, –∫–∞–∫–æ–π –º–µ—Ç–æ–¥ –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –¥–ª—è –ø–æ–∏—Å–∫–∞ –∏ —É–¥–∞–ª–µ–Ω–∏—è –¥—É–±–ª–∏–∫–∞—Ç–æ–≤;
- [x] –æ–ø–∏—Å–∞–Ω—ã –≤–æ–∑–º–æ–∂–Ω—ã–µ –ø—Ä–∏—á–∏–Ω—ã –ø–æ—è–≤–ª–µ–Ω–∏—è –¥—É–±–ª–∏–∫–∞—Ç–æ–≤ –≤ –¥–∞–Ω–Ω—ã—Ö;
- [x]  –≤—ã–¥–µ–ª–µ–Ω—ã –ª–µ–º–º—ã –≤ –∑–Ω–∞—á–µ–Ω–∏—è—Ö —Å—Ç–æ–ª–±—Ü–∞ —Å —Ü–µ–ª—è–º–∏ –ø–æ–ª—É—á–µ–Ω–∏—è –∫—Ä–µ–¥–∏—Ç–∞;
- [x]  –æ–ø–∏—Å–∞–Ω –ø—Ä–æ—Ü–µ—Å—Å –ª–µ–º–º–∞—Ç–∏–∑–∞—Ü–∏–∏;
- [x]  –¥–∞–Ω–Ω—ã–µ –∫–∞—Ç–µ–≥–æ—Ä–∏–∑–∏—Ä–æ–≤–∞–Ω—ã;
- [x]  –µ—Å—Ç—å –æ–±—ä—è—Å–Ω–µ–Ω–∏–µ –ø—Ä–∏–Ω—Ü–∏–ø–∞ –∫–∞—Ç–µ–≥–æ—Ä–∏–∑–∞—Ü–∏–∏ –¥–∞–Ω–Ω—ã—Ö;
- [x]  –µ—Å—Ç—å –æ—Ç–≤–µ—Ç –Ω–∞ –≤–æ–ø—Ä–æ—Å: "–ï—Å—Ç—å –ª–∏ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç—å –º–µ–∂–¥—É –Ω–∞–ª–∏—á–∏–µ–º –¥–µ—Ç–µ–π –∏ –≤–æ–∑–≤—Ä–∞—Ç–æ–º –∫—Ä–µ–¥–∏—Ç–∞ –≤ —Å—Ä–æ–∫?";
- [x]  –µ—Å—Ç—å –æ—Ç–≤–µ—Ç –Ω–∞ –≤–æ–ø—Ä–æ—Å: "–ï—Å—Ç—å –ª–∏ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç—å –º–µ–∂–¥—É —Å–µ–º–µ–π–Ω—ã–º –ø–æ–ª–æ–∂–µ–Ω–∏–µ–º –∏ –≤–æ–∑–≤—Ä–∞—Ç–æ–º –∫—Ä–µ–¥–∏—Ç–∞ –≤ —Å—Ä–æ–∫?";
- [x]  –µ—Å—Ç—å –æ—Ç–≤–µ—Ç –Ω–∞ –≤–æ–ø—Ä–æ—Å: "–ï—Å—Ç—å –ª–∏ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç—å –º–µ–∂–¥—É —É—Ä–æ–≤–Ω–µ–º –¥–æ—Ö–æ–¥–∞ –∏ –≤–æ–∑–≤—Ä–∞—Ç–æ–º –∫—Ä–µ–¥–∏—Ç–∞ –≤ —Å—Ä–æ–∫?";
- [x] –µ—Å—Ç—å –æ—Ç–≤–µ—Ç –Ω–∞ –≤–æ–ø—Ä–æ—Å: "–ö–∞–∫ —Ä–∞–∑–Ω—ã–µ —Ü–µ–ª–∏ –∫—Ä–µ–¥–∏—Ç–∞ –≤–ª–∏—è—é—Ç –Ω–∞ –µ–≥–æ –≤–æ–∑–≤—Ä–∞—Ç –≤ —Å—Ä–æ–∫?";
- [x]  –≤ –∫–∞–∂–¥–æ–º —ç—Ç–∞–ø–µ –µ—Å—Ç—å –≤—ã–≤–æ–¥—ã;
- [x]  –µ—Å—Ç—å –æ–±—â–∏–π –≤—ã–≤–æ–¥.